### PR TITLE
Fix for Set prototype resolution

### LINKED ISSUE #3788: "Realm is not defined" when iterating through Realm Sets using Jest
I'm getting the error: "ReferenceError: Realm is not defined" when attempting to iterate through a Realm set using Jest. 

Realm version: 10.5.0-beta.2 (although I've tested on 10.5.0-beta.1 as well)

Sample unit test:

```javascript
test("should work with the Set data type", async () => {
    const characterSchema = {
      name: "Character",
      primaryKey: "_id",
      properties: {
        _id: "objectId",
        name: "string",
        levelsCompleted: "int<>",
        inventory: "string<>",
      },
    };
    const realm = await Realm.open({
      schema: [characterSchema],
    });

    let link, hunter;
    realm.write(() => {
      link = realm.create("Character", {
        _id: new BSON.ObjectId(),
        name: "Link",
        inventory: ["elixir", "compass", "glowing shield"],
        levelsCompleted: [4, 9],
      });
      hunter = realm.create("Character", {
        _id: new BSON.ObjectId(),
        name: "Hunter",
        inventory: ["estus flask", "gloves", "rune"],
        levelsCompleted: [1, 2, 5, 24],
      });
    });
    
    hunter.inventory.forEach((inventoryItem) => {
      console.log("The hunter has an inventory item:", inventoryItem);
    });

    realm.write(() => {
      realm.delete(link);
      realm.delete(hunter);
    });
    // close the realm
    realm.close();
  });
```

Some notes:

* Switching from a forEach loop to an alternative iterator method will still result in the error. 
* If you comment out the `forEach` method in the jest test you will not get the Realm undefined error. 
* If this code (minus the jest specific stuff) is run outside of a jest suite, for instance in a js file, it runs fine without error.

### PR DESCRIPTION
**Pull request by fronck**
## What, How & Why?

Fix type resolution for Set so that it works under Jest, node, and RN.

This closes #3788

## ☑️ ToDos

* [x] 📝 Changelog entry
~* [ ] 📝 `Compatibility` label is updated or copied from previous entry~
~* [ ] 🚦 Tests~
~* [ ] 📝 Public documentation PR created or is not necessary~
~* [ ] 💥 `Breaking` label has been applied or is not necessary~

*If this PR adds or changes public API's:*
~* [ ] typescript definitions file is updated~
~* [ ] jsdoc files updated~
~* [ ] Chrome debug API is updated if API is available on React Native~

### CODE REVIEW

File: lib/collection-methods.js [hunk 1]
```diff
@@ -55,7 +55,8 @@ Object.defineProperty(iteratorPrototype, Symbol.iterator, {
 
 ['entries', 'keys', 'values'].forEach(function(methodName) {
     var method = function() {
-        const isSet = this instanceof Realm.Set;
+        // checks for Set datatype.  Required for compatibility with node.js, Jest, and RN
```
Comment (takameyer) [inline lib/collection-methods.js:58]:
```suggestion
        // checks for Set datatype.  Required for compatibility with node.js, Jest, and RN
        // instanceof Set is not performing correctly in Jest tests, so we need to use an alternate method 
```
is it only Jest?

**Review by takameyer — APPROVED** [review]
My only suggestion would be to add a failing test to this PR. Otherwise LGTM

**Review by kneth — APPROVED** [review]
We might apply the same trick to Dictionary.

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,8 +4,8 @@ x.x.x Release notes (yyyy-MM-dd)
 * None.
 
 ### Fixed
-* Fixed TypeScript definition of `Realm.Dictionary.remove()`. (since v10.6.0)
-* Fixed Realm.Object#toJSON as it threw "Right-hand side of 'instanceof' is not an object". (since v10.6.0)
+* Fix TypeScript definition of `Realm.Dictionary.remove()`. (since v10.6.0)
```
Comment (fronck) [inline CHANGELOG.md:7]:
```suggestion
* Fixed TypeScript definition of `Realm.Dictionary.remove()`. (since v10.6.0)
* Fixed Realm.Object#toJSON as it threw "Right-hand side of 'instanceof' is not an object". (since v10.6.0)
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -6,6 +6,7 @@ x.x.x Release notes (yyyy-MM-dd)
 ### Fixed
 * Fixed TypeScript definition of `Realm.Dictionary.remove()`. (since v10.6.0)
 * Fixed Realm.Object#toJSON as it threw "Right-hand side of 'instanceof' is not an object". (since v10.6.0)
+* Fixed `Realm not defined` error experienced when using `Realm.Set` iterators under Jest
```
Comment (fronck) [inline CHANGELOG.md:9]:
```suggestion
* Fixed `Realm not defined` error experienced when using `Realm.Set` iterators under Jest  (closes #3788)
```
