### PR TITLE
`useUser` fixes for Realm React

### LINKED ISSUE #6196: Mismatch type when passing `user`  from `useUser` as parameter
### How frequently does the bug occur?

Always

### Description

As the [documentation](https://www.mongodb.com/docs/realm/sdk/react-native/manage-users/authenticate-users/) suggested, we can pass the `user` to a function. 

```typescript

// Gets a valid user access token to authenticate requests
async function getValidAccessToken(user: Realm.User) {
// An already logged in user's access token might be stale. To
// guarantee that the token is valid, refresh it if necessary.
await user.refreshCustomData();
 
return user.accessToken;
}

```

However, when passing the `user` from `useUser()`. following error display. 

```
Argument of type
User<DefaultFunctionsFactory, Record<string, unknown>, DefaultUserProfileData>
is not assignable to parameter of type
UserType<UserFunctionsType, UserCustomDataType, UserProfileDataType>
Types have separate declarations of a private property  cachedProfile 
```

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Always

### Reproduction Steps

`file1.ts`
```typescript
import Realm from 'realm';

export function foo(user: Realm.User){
  // Do something
}

```

`file2.ts`
```typescript
import {foo} from file1;

const user = useUser();
foo(user);
```

### Version

"realm": "^12.2.1",, "@realm/react": "^0.6.0",

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

Win11 23H2

### Build environment

Which debugger for React Native: ..

### Cocoapods version

_No response_

### PR DESCRIPTION
**Pull request by takameyer**
## What, How & Why?
* Used a different type declaration generation method which solved typing issues
* Updated `UserProvider` to always update the user reference on user events
* Updated connection example to include a delete user function to test this feature

This closes #6196 and #6186

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [ ] 🚦 Tests
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

File: examples/rn-connection-and-error/frontend/app/components/Button.tsx [hunk 1]
```diff
@@ -64,6 +64,7 @@ const styles = StyleSheet.create({
     borderRadius: 30,
     borderColor: colors.purple,
     backgroundColor: colors.purple,
+    justifyContent: 'center',
```
Comment (elle-j) [inline examples/rn-connection-and-error/frontend/app/components/Button.tsx:67]: I believe this may be unnecessary (no effect).

File: packages/realm-react/src/UserProvider.tsx [hunk 2]
```diff
@@ -49,9 +49,10 @@ export const UserProvider: React.FC<UserProviderProps> = ({ fallback: Fallback,
 
   useEffect(() => {
     const event = () => {
-      if (app.currentUser?.id != user?.id) {
-        setUser(app.currentUser);
-      }
+      console.log("UserProvider: user changed");
+      console.log("UserProvider: app.currentUser", app.currentUser);
+      console.log("UserProvider: app.currentUser.id", app.currentUser);
```
Comment (elle-j) [inline packages/realm-react/src/UserProvider.tsx:54]:
```suggestion
```

File: packages/realm-react/src/UserProvider.tsx [hunk 3]
```diff
@@ -49,9 +49,10 @@ export const UserProvider: React.FC<UserProviderProps> = ({ fallback: Fallback,
...
+      setUser(app.currentUser);
```
Comment (elle-j) [inline packages/realm-react/src/UserProvider.tsx:55]: 🙂

**Review by elle-j — COMMENTED** [review]
Awesome to get this fix in! LGTM when [this PR](https://github.com/realm/realm-js/pull/6208) is merged into the current one 🙂

File: packages/realm-react/package.json [hunk 4]
```diff
@@ -16,7 +16,7 @@
   },
   "wireit": {
     "bundle": {
-      "command": "rollup --config",
+      "command": "rollup --config && tsc -p tsconfig.types.json",
```
Comment (kraenhansen) [inline packages/realm-react/package.json:19]: Should this be a separate `types` command? Since technically this isn't bundling the types now.

File: packages/realm-react/tsconfig.types.json [hunk 5]
```diff
@@ -0,0 +1,11 @@
+{
+  "extends": "./tsconfig.json",
+  "compilerOptions": {
+    "declaration": true,
+    "emitDeclarationOnly": true,
+    "outDir": "./dist",
```
Comment (kraenhansen) [inline packages/realm-react/tsconfig.types.json:6]: Consider adding https://www.typescriptlang.org/tsconfig#incremental and https://www.typescriptlang.org/tsconfig#declarationMap too.

File: examples/rn-connection-and-error/frontend/app/components/Button.tsx (hunk 1 above)
Comment (takameyer) [reply examples/rn-connection-and-error/frontend/app/components/Button.tsx:67]: It was intentional.  This centers vertically within the button container.

File: packages/realm-react/package.json (hunk 4 above)
Comment (takameyer) [reply packages/realm-react/package.json:19]: As our ci assumes a single command for preparing packages for release, I would be hesitant to put this in a separate command.
Otherwise, we can make a follow up PR which adds a `types` command to every package (or simply `build`, which contains `bundle` and `types`) and update our workflows to call this as well.

File: examples/rn-connection-and-error/frontend/app/components/Button.tsx (hunk 1 above)
Comment (takameyer) [reply examples/rn-connection-and-error/frontend/app/components/Button.tsx:67]: Specifically "Refresh Access Token" was on two lines and this caused the height of the button on this row to change.

File: packages/realm-react/src/UserProvider.tsx (hunk 3 above)
Comment (takameyer) [reply packages/realm-react/src/UserProvider.tsx:52]: Somehow I lost the change I actually wanted to commit.  This line is now
```
setUser( app.currentUser ? new Proxy(app.currentUser, {}) : null );
```

File: examples/rn-connection-and-error/frontend/app/components/Button.tsx (hunk 1 above)
Comment (takameyer) [reply examples/rn-connection-and-error/frontend/app/components/Button.tsx:67]: image

Comment (takameyer) [reply examples/rn-connection-and-error/frontend/app/components/Button.tsx:67]: image
without change

Comment (elle-j) [reply examples/rn-connection-and-error/frontend/app/components/Button.tsx:67]: Ok great 🙂 Was using a wider screen 😛

File: packages/realm-react/src/UserProvider.tsx (hunk 3 above)
Comment (elle-j) [reply packages/realm-react/src/UserProvider.tsx:52]: Is it worth adding a test for this btw?

Comment (takameyer) [reply packages/realm-react/src/UserProvider.tsx:52]: It's worth it, but I don't have time, but I'm not actually scheduled to work on this right now.  I just want things to work.  
The UserProvider needs tests, at the time of creation it wasn't clear how to deploy an app for functional testing, but now we can do this.

**Review by kneth — APPROVED** [review]

File: packages/realm-react/src/UserProvider.tsx (hunk 3 above)
Comment (takameyer) [reply packages/realm-react/src/UserProvider.tsx:52]: https://github.com/realm/realm-js/issues/6212. For the next phase of `realm react` we have planned

Comment (elle-j) [reply packages/realm-react/src/UserProvider.tsx:52]: Great!

File: packages/realm-react/package.json (hunk 4 above)
Comment (takameyer) [reply packages/realm-react/package.json:19]: I put this in our next roundtable.  I think you bring up a good point.

My suggestion is to create a script in each of our mono-repo packages called `prepack`, which can include whatever scripts it needs to prepare for being consumed by another project.  This could include `bundle`, `generateTypes`, `build`, etc.
Then the CI workflows would be updated to run this command instead of `bundle`.

Comment (kraenhansen) [reply packages/realm-react/package.json:19]: It was the idea that these inter-package task dependencies should be configured via wireit. It's much more capable as it'll cache outputs and potentially execute tasks in parallel.

File: packages/realm-react/src/UserProvider.tsx (hunk 3 above)
Comment (elle-j) [reply packages/realm-react/src/UserProvider.tsx:52]: FYI, looks like the `new Proxy()` implementation was never committed.

Comment (takameyer) [reply packages/realm-react/src/UserProvider.tsx:52]: 🤯

Comment (takameyer) [reply packages/realm-react/src/UserProvider.tsx:52]: Must be a rebase issue.  Guess that's why we should write tests :D

File: packages/realm-react/package.json (hunk 4 above)
Comment (takameyer) [reply packages/realm-react/package.json:19]: I don't disagree, I just want to unify on a script that specifically deals with preparing for release.
