### PR TITLE
Fix error that caused a segfault when users registered custom Sync logger functions

### LINKED ISSUE #4121: Segmentation fault when performing await realm.open(config)
### How frequently does the bug occur?

All the time

### Description

Trying to load an existing local realm file into a test MongoDB Realm App and using a node.js script to do so.  However when calling realm.open() we are getting a segmentation fault.

Node v16.13.0
realm-js v10.10.1

log in appears to work fine but the subsequent call results in a segmentation fault.

```
const realmConfig = {
        schema: target_realm_schema,
        sync: {
            user: app.currentUser,
            partitionValue: partitionKey,
            // The behavior to use when this is the first time opening a realm.
            newRealmFileBehavior: {
                type: "downloadBeforeOpen",
                timeout: 120,
                timeOutBehaviour: "openLocalRealm"
            },
            // The behavior to use when a realm file already exists locally,
            // i.e. you have previously opened the realm.
            existingRealmFileBehavior: {
                type: "openImmediately",
                timeout: 30,
                timeOutBehaviour: "openLocalRealm"
            },
        },
    };

    log("async open realm...")
    const target_realm = await Realm.open(realmConfig);
```

Anyone have any suggestions on how to debug the cause of the segmentation fault ?

Is the realm-js compatible with node v16.13.0 ?

Thanks

### Stacktrace & log output

```shell
There is no stack trace.
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Script can be provided 

### Version

V10.10.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS 12.0.1

### Build environment

Which debugger for React Native: N/A

Here is the set fault

PID 90660 received SIGSEGV for address: 0x3
0   segfault-handler.node               0x0000000106bd1458 _ZL16segfault_handleriP9__siginfoPv + 272
1   libsystem_platform.dylib            0x000000019a6584e4 _sigtramp + 56
2   realm.node                          0x000000010f7a5928 _ZZN5realm6common6logger6Logger17build_sync_loggerERNSt3__18functionIFviNS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEEENKUlNS_4util6Logger5LevelEE_clESG_ + 172
3   realm.node                          0x000000010f7a5928 _ZZN5realm6common6logger6Logger17build_sync_loggerERNSt3__18functionIFviNS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEEEEENKUlNS_4util6Logger5LevelEE_clESG_ + 172
4   realm.node                          0x000000010f7a57e0 _ZNSt3__110__function6__funcIZN5realm6common6logger6Logger17build_sync_loggerERNS_8functionIFviNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEEEUlNS2_4util6Logger5LevelEE_NSA_ISJ_EEFNS_10unique_ptrISH_NS_14default_deleteISH_EEEESI_EEclEOSI_ + 36
5   realm.node                          0x000000010f8d394c _ZNK5realm11SyncManager18create_sync_clientEv + 68
6   realm.node                          0x000000010f8d2a48 _ZN5realm11SyncManager11get_sessionENSt3__110shared_ptrINS_2DBEEERKNS_10SyncConfigE + 92
7   realm.node                          0x000000010f87731c _ZN5realm5_impl16RealmCoordinator19create_sync_sessionEv + 204
8   realm.node                          0x000000010f879d24 _ZN5realm5_impl16RealmCoordinator22get_synchronized_realmENS_5Realm6ConfigE + 88
9   realm.node                          0x000000010f850538 _ZN5realm5Realm22get_synchronized_realmENS0_6ConfigE + 108
10  realm.node                          0x000000010f6b85f8 _ZN5realm2js10RealmClassINS_4node5TypesEE16async_open_realmEN4Napi3EnvENS5_6ObjectERNS0_9ArgumentsIS3_EERNS0_11ReturnValueIS3_EE + 652
11  realm.node                          0x000000010f69ebf4 _ZN5realm2js4wrapIXadL_ZNS0_10RealmClassINS_4node5TypesEE16async_open_realmEN4Napi3EnvENS6_6ObjectERNS0_9ArgumentsIS4_EERNS0_11ReturnValueIS4_EEEEEENS6_5ValueERKNS6_12CallbackInfoE + 244
12  realm.node                          0x000000010f6ed4b0 _ZN4Napi7details12WrapCallbackIZNS_10ObjectWrapIN5realm4node13WrappedObjectINS3_2js10RealmClassINS4_5TypesEEEEEE27StaticMethodCallbackWrapperEP10napi_env__P20napi_callback_info__EUlvE_EEP12napi_value__T_ + 60
13  realm.node                          0x000000010f6ed468 _ZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE27StaticMethodCallbackWrapperEP10napi_env__P20napi_callback_info__ + 28
14  node                                0x000000010242c6f8 _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE + 104
15  node                                0x000000010262032c _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE + 276
16  node                                0x000000010261fe24 _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE + 468
17  node                                0x000000010261f6b0 _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE + 228
18  node                                0x0000000102d5d1cc Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 108
19  node                                0x0000000102cf0d18 Builtins_InterpreterEntryTrampoline + 248
20  node                                0x0000000102da3700 Builtins_PromiseConstructor + 2176
21  node                                0x0000000102cedf50 Builtins_JSBuiltinsConstructStub + 368
22  node                                0x0000000102dec070 Builtins_ConstructHandler + 656
23  node                                0x0000000102cf0d18 Builtins_InterpreterEntryTrampoline + 248
24  node                                0x0000000102cf0d18 Builtins_InterpreterEntryTrampoline + 248
25  node                                0x0000000102cf0d18 Builtins_InterpreterEntryTrampoline + 248
26  node                                0x0000000102d20314 Builtins_AsyncFunctionAwaitResolveClosure + 84
27  node                                0x0000000102da51b8 Builtins_PromiseFulfillReactionJob + 56
28  node                                0x0000000102d126f4 Builtins_RunMicrotasks + 596
29  node                                0x0000000102cee9e4 Builtins_JSRunMicrotasksEntry + 164
30  node                                0x00000001026c31e8 _ZN2v88internal12_GLOBAL__N_16InvokeEPNS0_7IsolateERKNS1_12InvokeParamsE + 2332
31  node                                0x00000001026c361c _ZN2v88internal12_GLOBAL__N_118InvokeWithTryCatchEPNS0_7IsolateERKNS1_12InvokeParamsE + 88

### PR DESCRIPTION
**Pull request by fronck**
## What, How & Why?

This closes #4121 

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [x] 🚦 Tests
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Review by kraenhansen — APPROVED** [review]
Great job. Was it basically that the function provided by the user was not owned by SyncLoggerDelegator and was therefore free to be garbage collected, eventually leading to a use after free of the callback?

File: tests/js/session-tests.js [hunk 1]
```diff
@@ -527,6 +527,24 @@ module.exports = {
...
+    let user = await app.logIn(credentials);
+    let config = getSyncConfiguration(user, partition);
+
+    let loggerInvoked = false;
+    Realm.App.Sync.setLogLevel(app, "info"); // "all", "trace", "debug", "detail", "info", "warn", "error", "fatal", "off"
+    Realm.App.Sync.setLogger(app, (level, message) => (loggerInvoked = true));
+    const realm = await Realm.open(config);
+    realm.close();
+
+    TestCase.assertTrue(loggerInvoked, "Custom logger should have been invoked");
```
Comment (kneth) [inline tests/js/session-tests.js:545]: I am a bit worry for a race condition here but maybe `Realm.open()` takes long enough.

**Review by kneth — APPROVED** [review]
Awesome ❤️

File: tests/js/session-tests.js (hunk 1 above)
Comment (kraenhansen) [inline tests/js/session-tests.js:545]: I agree, this could instead await the logger callback being called.

```suggestion
    const promisedLog = new Promise(resolve => {
        Realm.App.Sync.setLogLevel(app, "info"); // "all", "trace", "debug", "detail", "info", "warn", "error", "fatal", "off"
        Realm.App.Sync.setLogger(app, (level, message) => resolve(message));
    });
    const realm = await Realm.open(config);
    const message = await promisedLog;
    realm.close();

    TestCase.assertEqual(message, /* whatever the first message will be */);
```

**Comment by tomduncalf** [comment]
> Great job. Was it basically that the function provided by the user was not owned by SyncLoggerDelegator and was therefore free to be garbage collected, eventually leading to a use after free of the callback?

My understanding is that the [`show_logs` `std::function`](https://github.com/realm/realm-js/blob/83ffa3fd2fd94b3c450f86248602d12ee4711e9e/src/js_sync.hpp#L822) was going out of scope at the end of the `set_sync_logger` method and as nothing else had taken ownership of it, it was being destructed immediately at that time... so by the time something tried to log and [`make_logger`](https://github.com/realm/realm-core/blob/master/src/realm/object-store/sync/sync_manager.cpp#L274) was called, it no longer existed. Franck may be able to correct any misunderstandings I have though :) 

In the old implementation, there was a [`SyncLoggerDelegatorFactory` class](https://github.com/realm/realm-js/commit/535bea5f2aa680fca4fb51f45d0fc2cefb66e153#diff-e112fb3700a88222a5435b4b508684f851f0e2b0ba7e0d2b7a024a23c5e18421L115) which retained ownership of the function.

File: tests/js/session-tests.js [hunk 2]
```diff
@@ -527,6 +527,24 @@ module.exports = {
...
+  async testCustomSessionLogging() {
+    const partition = Utils.genPartition();
+    let credentials = Realm.Credentials.anonymous();
+    let app = new Realm.App(appConfig);
+    let user = await app.logIn(credentials);
+    let config = getSyncConfiguration(user, partition);
+
+    let loggerInvoked = false;
+    Realm.App.Sync.setLogLevel(app, "info"); // "all", "trace", "debug", "detail", "info", "warn", "error", "fatal", "off"
+    Realm.App.Sync.setLogger(app, (level, message) => (loggerInvoked = true));
```
Comment (tomduncalf) [inline tests/js/session-tests.js:541]: I guess it might not hurt to test that `level` and `message` are passed through correctly?

```suggestion
    let loggedLevel, loggedMessage;
    Realm.App.Sync.setLogLevel(app, "info"); // "all", "trace", "debug", "detail", "info", "warn", "error", "fatal", "off"
    Realm.App.Sync.setLogger(app, (level, message) => {
      if (!loggedLevel) loggedLevel = level;
      if (!loggedMessage) loggedMessage = message;
    });
    
    // ...
    
    TestCase.assertEqual(loggedLevel, 123);
    TestCase.assertEqual(loggedMessage, "whatever the first message is");
```

Or is the first message not predictable?

**Review by tomduncalf — APPROVED** [review]

File: tests/js/session-tests.js (hunk 1 above)
Comment (fronck) [reply tests/js/session-tests.js:545]: I'm not sure we can say for certain what the first message will be.  Maybe we can just `resolve(true)`?

Comment (tomduncalf) [reply tests/js/session-tests.js:545]: If we don't know for sure what the first message is then I think the current way seems fine 👍

File: tests/js/session-tests.js (hunk 2 above)
Comment (fronck) [reply tests/js/session-tests.js:541]: It is as long as the sync subsystem doesn't change what it returns, or the sync config structure doesn't change.  It'd be weird if the test failed because of that, but I'll see if I can parse out from the lower levels how the message is constructed.

**Comment by fronck** [comment]
> > Great job. Was it basically that the function provided by the user was not owned by SyncLoggerDelegator and was therefore free to be garbage collected, eventually leading to a use after free of the callback?
> 
> My understanding is that the [`show_logs` `std::function`](https://github.com/realm/realm-js/blob/83ffa3fd2fd94b3c450f86248602d12ee4711e9e/src/js_sync.hpp#L822) was going out of scope at the end of the `set_sync_logger` method and as nothing else had taken ownership of it, it was being destructed immediately at that time... so by the time something tried to log and [`make_logger`](https://github.com/realm/realm-core/blob/master/src/realm/object-store/sync/sync_manager.cpp#L274) was called, it no longer existed. Franck may be able to correct any misunderstandings I have though :)
> 
> In the old implementation, there was a [`SyncLoggerDelegatorFactory` class](https://github.com/realm/realm-js/commit/535bea5f2aa680fca4fb51f45d0fc2cefb66e153#diff-e112fb3700a88222a5435b4b508684f851f0e2b0ba7e0d2b7a024a23c5e18421L115) which retained ownership of the function.

Yes, basically we were passing `log_fn` around by reference, so when it went out of scope, we left a dangling pointer to a function that wasn't safe to invoke.

File: tests/js/session-tests.js (hunk 2 above)
Comment (tomduncalf) [reply tests/js/session-tests.js]: I wouldn't worry too much if it's awkward :)

**Review by kraenhansen — APPROVED** [review]
I have a minor comment here - feel free to integrate the suggestion or merge at will.
