### PR TITLE
RJS-2760: Adding `Realm.shutdown()` and fixing clean exit tests

### LINKED ISSUE #6555: Implement Realm.shutdown()
Implement a method to gracefully terminate and clean up resources used the Realm. This is in particular useful in Electron apps where new versions of the app are installed remotely and unattended.

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

This closes #6555, #5781, #4535, #6096, #6357, #4530, #3616 by adding a static `Realm.shutdown` method, which closes all Realms, cancels all pending `Realm.open` calls, clears internal caches, resets the logger and collects garbage.

## ☑️ ToDos
* [x] 📝 Changelog entry
* [x] 📝 `Compatibility` label is updated or copied from previous entry
* [x] 📝 Update `COMPATIBILITY.md`
* [x] 🚦 Tests
* [x] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [x] 📱 Check the React Native/other sample apps work if necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

File: integration-tests/tests/src/node/clean-exit.ts [hunk 1]
```diff
@@ -16,16 +16,50 @@
...
+    cwd: fs.mkdtempSync(path.join(os.tmpdir(), "realm-exit-test-")),
+    stdio: "inherit",
+    env: {
+      REALM_PACKAGE_PATH: realmPackagePath,
+    },
+  });
+}
+
+describe("clean exits in Node.js", function () {
   // Repro for https://github.com/realm/realm-js/issues/4535 - currently still failing
```
Comment (elle-j) [inline integration-tests/tests/src/node/clean-exit.ts:42]:
```suggestion
```

File: packages/realm/src/platform/garbage-collection.ts [hunk 2]
```diff
@@ -0,0 +1,27 @@
+////////////////////////////////////////////////////////////////////////////
+//
+// Copyright 2022 Realm Inc.
```
Comment (elle-j) [inline packages/realm/src/platform/garbage-collection.ts:3]:
```suggestion
// Copyright 2024 Realm Inc.
```

**Review by elle-j — APPROVED** [review]
Great debugging session 🥳

**Review by kneth — APPROVED** [review]

**Comment by kraenhansen** [comment]
Rebased on `main` which has the changes we need with #6598.

**Comment by kraenhansen** [comment]
Coverage test is still crashing (#6589) but that's not new - I'll go ahead and merge with it.
