### PR TITLE
Fix SessionTests.testNonAcceptedPartitionValueTypes

### LINKED ISSUE #5064: Validate partition values in config validation
The SessionTests.testNonAcceptedPartitionValueTypes are failing, indicating that invalid partition values can be sent to the server.

### PR DESCRIPTION
**Pull request by JacobOscarGunnarsson**
Added validation for the `PartitionValue` provided when opening a `Realm`
This closes #5064

### CODE REVIEW

File: packages/realm/src/app-services/SyncConfiguration.ts [hunk 1]
```diff
@@ -113,3 +114,26 @@ export function toBindingSyncConfig(config: SyncConfiguration): binding.SyncConf
       : binding.SyncSessionStopPolicy.AfterChangesUploaded,
   };
 }
+
+/** @internal */
+function validatePartitionValue(partitionValue: unknown) {
+  if (partitionValue === undefined) {
+    throw new Error(partitionValue + " is not an allowed PartitionValue");
+  }
+  if (typeof partitionValue == "number") {
```
Comment (takameyer) [inline packages/realm/src/app-services/SyncConfiguration.ts:123]:
```suggestion
  if (typeof partitionValue === "number") {
```
In general, I think `===` should be used instead of `==`, unless you have a reason to do so. `==` has so many edge cases, that it's possible to get some false positives if you don't know what it's doing.
In this case, it doesn't make much of a difference, as `typeof` will always return a string and `"number"` is also always going to be a string.  
For more on the matter: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness

File: packages/realm/src/app-services/SyncConfiguration.ts [hunk 2]
```diff
@@ -113,3 +114,26 @@ export function toBindingSyncConfig(config: SyncConfiguration): binding.SyncConf
       : binding.SyncSessionStopPolicy.AfterChangesUploaded,
   };
 }
+
+/** @internal */
+function validatePartitionValue(partitionValue: unknown) {
+  if (partitionValue === undefined) {
```
Comment (takameyer) [inline packages/realm/src/app-services/SyncConfiguration.ts:120]: We are missing a few other invalid cases here.  I would try and mirror what was written before in c++ (https://github.com/realm/realm-js/blob/master/src/js_sync.hpp#L77-L104)
For instance, currently the types `boolean`, `Date`, `Object`, `Array`, etc would all pass this validation.  In this case, I would verify that the value is typeof `string`, `number`, `objectId` or `null`.  If it isn't one of those, then throw.

**Review by takameyer — CHANGES_REQUESTED** [review]

File: packages/realm/src/app-services/SyncConfiguration.ts (hunk 1 above)
Comment (JacobOscarGunnarsson) [reply packages/realm/src/app-services/SyncConfiguration.ts:123]: hehe I think it was mostly my muscle memory that went for the `==`, I've also heard rumours about `==` being iffy in JS so I'll change it!

File: tests/js/session-tests.js [hunk 3]
```diff
@@ -1046,6 +1046,9 @@ module.exports = {
 
   async testNonAcceptedPartitionValueTypes() {
     const testPartitionValues = [
+      true,
```
Comment (JacobOscarGunnarsson) [inline tests/js/session-tests.js:1049]: this addition may not be necessary but I see no harm in adding them as well

**Review by takameyer — APPROVED** [review]
Looks good!
