### PR TITLE
Realn.User.callFunction() defaults to an empty array as argument

### LINKED ISSUE #3718: user.callFunction returns 'Assertion failed' if called with no args instead of simple error
## Note
I am reporting this issue as I see the following message in the terminal 

`IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new`

## Goals
Call a simple function which requires no args as authenticated user.

## Expected Results
{{user.callFunction("some_function_name") }}

should either throw a simple error explaining that `callFunction` expects  both name and args or default args to empty array if none are passed.

## Actual Results
```
./vendor/realm-core/src/realm/object-store/util/bson/bson.hpp:201: [realm-core-10.6.0] Assertion failed: m_type == Bson::Type::Array
0   realm.node                          0x0000000105d8752c _ZN5realm4utilL18terminate_internalERNSt3__118basic_stringstreamIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 28
1   realm.node                          0x0000000105d8782b _ZN5realm4util9terminateEPKcS2_lOSt16initializer_listINS0_9PrintableEE + 395
2   realm.node                          0x00000001058cb986 _ZN5realm2js9UserClassINS_4node5TypesEE13call_functionEN4Napi3EnvENS5_6ObjectERNS0_9ArgumentsIS3_EERNS0_11ReturnValueIS3_EE + 1174
3   realm.node                          0x00000001058c6315 _ZN5realm2js4wrapIXadL_ZNS0_9UserClassINS_4node5TypesEE13call_functionEN4Napi3EnvENS6_6ObjectERNS0_9ArgumentsIS4_EERNS0_11ReturnValueIS4_EEEEEENS6_5ValueERKNS6_12CallbackInfoE + 293
4   realm.node                          0x00000001058ce57b _ZZN4Napi12InstanceWrapIN5realm4node13WrappedObjectINS1_2js9UserClassINS2_5TypesEEEEEE29InstanceMethodCallbackWrapperEP10napi_env__P20napi_callback_info__ENKUlvE_clEv + 139
5   realm.node                          0x00000001058ce49a _ZN4Napi12InstanceWrapIN5realm4node13WrappedObjectINS1_2js9UserClassINS2_5TypesEEEEEE29InstanceMethodCallbackWrapperEP10napi_env__P20napi_callback_info__ + 42
6   node                                0x000000010005eefa _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE + 122
7   node                                0x000000010024a488 _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE + 616
8   node                                0x0000000100249a49 _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE + 521
9   node                                0x00000001002491b2 _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE + 258
10  node                                0x00000001009ce9d9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
11  node                                0x0000000100954284 Builtins_InterpreterEntryTrampoline + 676!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choosesh
```

## Steps to Reproduce
Define a function named 'test_function' like so in the realm UI and in the settings allow an api-key authenticated user to call it via user id authentication. 

```
exports = function() {
  return "HELLO";
};
```

From node log in a user and try call the function without passing args.

```
const app = new App({ id: appId });

const credentials = Credentials.serverApiKey(apiKey);

const user = await app.logIn(credentials);

user.callFunction('test_function');
```

## Version of Realm and Tooling
* Realm JS SDK Version: ^10.4.0
* Node: 12.18.2
* Client OS & Version: macOS Mojave 10.14.6

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

This closes #3718

## ☑️ ToDos

* [x] 📝 Changelog entry
* ~[ ] 📝 `Compatibility` label is updated or copied from previous entry~
* [x] 🚦 Tests
* ~[ ] 📝 Public documentation PR created or is not necessary~
* ~[ ] 💥 `Breaking` label has been applied or is not necessary~

*If this PR adds or changes public API's:*
* ~[ ] typescript definitions file is updated~
* [x] jsdoc files updated
* ~[ ] Chrome debug API is updated if API is available on React Native~

### CODE REVIEW

File: docs/sync.js [hunk 1]
```diff
@@ -698,7 +698,7 @@ class User {
     /**
      * Calls the named server function as this user.
      * @param {string} name - name of the function to call
-     * @param {any[]} args - list of arguments to pass
+     * @param {any[]} args - list of arguments to pass, if no arguments are passes, `[]` is used
      * @return {Promise<any>} - resolves when the function terminates.
      */
     callFunction(name, args) { }
```
Comment (RedBeard0531) [inline docs/sync.js:704]: Can you do `args = []` here? I prefer putting things like that in code, rather than prose, although the esdoc html generator has some weird limitations. If not, you should probably at least change the type on line 701 to indicate optionality.

Also, we need to fix this since it is extremely wrong... https://github.com/realm/realm-js/blob/364448f3267e4f733018a248fe7d5a370f625a15/types/app.d.ts#L495

File: lib/user.js [hunk 2]
```diff
@@ -33,6 +33,9 @@ const instanceMethods = {
     },
 
     async callFunction(name, args, service = undefined) {
+        if (!args) {
```
Comment (RedBeard0531) [inline lib/user.js:36]: Why do this rather than `args = []` in the function signature?

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,11 +1,26 @@
-10.4.1-rc.3 Release notes (2021-5-10)
+x.x.x Release notes (yyyy-MM-dd)
 =============================================================
 ### Enhancements
 * None.
 
 ### Fixed
 * Fixed the naming of `url` (now `baseUrl`) property on an app config to match the TypeScript declaration and other SDKs. ([#3612](https://github.com/realm/realm-js/issues/3612))
```
Comment (RedBeard0531) [inline CHANGELOG.md:7]: Was it correct to move this from `10.4.1-rc.3` to `x.x.x`? Is this just fixing a bug that it was in the wrong place before, or are you introducing a bug by moving it?

**Review by RedBeard0531 — CHANGES_REQUESTED** [review]

File: docs/sync.js (hunk 1 above)
Comment (kraenhansen) [reply docs/sync.js:704]: Just to make this obvious. The types you're referring to are shared with Realm Web.
I've created an issue to track fixing this: https://github.com/realm/realm-js/issues/3733

File: CHANGELOG.md (hunk 3 above)
Comment (kneth) [reply CHANGELOG.md:7]: I forgot to add the template when I merged a PR yesterday so I am fixing it now.

**Review by kraenhansen — APPROVED** [review]
Looking good 🚢

**Review by RedBeard0531 — APPROVED** [review]
I'd rather we update the .d.ts files to reflect the correct types in this commit, but if there are reasons why we can't, I'm fine with deferring.

**Comment by steffenagger** [comment]
> I'd rather we update the .d.ts files to reflect the correct types in this commit, but if there are reasons why we can't, I'm fine with deferring.

Our current TS declaration is:
```ts
callFunction(name: string, ...args: any[]): Promise<any>;
```
Thats not right if `callFunction` previously expected an array as second param? (@kraenhansen does realm-web handle this differently?)

Now it should just be:
```ts
callFunction(name: string, args?: any[]): Promise<any>;
```
right?

**Comment by kneth** [comment]
@RedBeard0531 @steffenagger I believe that https://github.com/realm/realm-js/issues/3733 is trying to capture your concerns.
