### PR TITLE
Fixed `User#callFunction` arguments, passing them correctly to the server

### LINKED ISSUE #6447: User function arguments is wrapped in an Array
### How frequently does the bug occur?

Always

### Description

Breaking issue in 12.6.0
User function argument sent to Atlas is wrapped in an Array 

the problem is in this file, (idk where is this issue in the source repo)
./node_modules/realm/dist/bundle.react-native.js
line ~7600 

```typescript
callFunction(name, ...args) {
    return this.callFunctionOnService(name, undefined, args);
}
```

As you can see, the function received spread variable arguments, but then you passed it to `callFunctionOnService` as one array variable

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Always

### Reproduction Steps

Just install realm 12.6.0 in a react-native project

### Version

12.6.0

### What services are you using?

Atlas App Services: Functions or GraphQL or DataAPI etc

### Are you using encryption?

No

### Platform OS and version(s)

WSL Ubuntu on Windows

### Build environment

Which debugger for React Native: ..
none

### Cocoapods version

_No response_

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

This closes #6447 by correctly spreading in the `args` when calling `callFunctionOnService`.

I also fixed the test that was passing, because we had wrapped the function being tested in a `parseInt`, which sadly coerced the `[123]` into `123`, making the test pass although the code was broken.

Credit for discovering and proposing a fix for the bug goes to @deckyfx - thanks again!

## ☑️ ToDos
* [x] 📝 Changelog entry
* [x] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [x] 🚦 Tests
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

File: packages/realm/src/app-services/utils.ts [hunk 1]
```diff
@@ -16,11 +16,15 @@
...
+import { binding } from "src/internal";
+
 /**
  * Remove entries for undefined property values.
  * @internal
  */
-export function cleanArguments(args: unknown[] | unknown): unknown[] | unknown {
+export function cleanArguments(args: unknown[]): binding.EJson[];
+export function cleanArguments(args: unknown): binding.EJson;
+export function cleanArguments(args: unknown[] | unknown) {
```
Comment (kraenhansen) [inline packages/realm/src/app-services/utils.ts:27]: While I was at it, I updated the signature of this, to avoid type assertions on the calling side.

**Review by kneth — APPROVED** [review]
