### PR TITLE
Setter must replace embedded object instead of add a new object

### LINKED ISSUE #6239: Updating an element within an array of embedded schema behaves differently on Realm 12 and 11
### How frequently does the bug occur?

Always

### Description

Realm 11.9.0 and 12.0.0 have different behavior when updating an element in an array within an embedded schema. If a change is desired, how can an element be updated in this case?

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Always

### Reproduction Steps

I've created an example to show the difference between Realm 12.0.0 and 11.9.0.

https://github.com/andreyukD/reproduce-realmjs-issue

Starting point was `npx create-expo-app MyAwesomeRealmApp --template @realm/expo-template`

I've added a new field `items` in `Task` schema
 
Commit with v12 https://github.com/andreyukD/reproduce-realmjs-issue/commit/897316aa157562b4724c5272c0dea90953919b9d

Branch with v11, code remained unchanged, only the Realm version was updated https://github.com/andreyukD/reproduce-realmjs-issue/commits/v11

https://github.com/realm/realm-js/assets/33383393/1cb8a88d-6c76-4c45-8614-8bb30673bb95

https://github.com/realm/realm-js/assets/33383393/262b46f0-7700-4e74-ad2d-e20235292a57

### Version

12.0.0 / 11.9.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 14.0

### Build environment

Which debugger for React Native: ..

### Cocoapods version

_No response_

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

When replacing an element in a list of embedded object, the existing object should be removed. Calling `Obj::set_embedded()` is replacing while `Obj::insert_embedded()` will create a new object and add it to the list without touching the existing element.

This closes #6239 

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [x] 🚦 Tests
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

File: integration-tests/tests/src/tests/list.ts [hunk 1]
```diff
@@ -2126,13 +2130,23 @@ describe("Lists", () => {
         ib.addresses.push({ street: "Njalsgade", city: "Islands Brygge" });
         expect(3).equals(ib.addresses.length);
```
Comment (elle-j) [inline integration-tests/tests/src/tests/list.ts:2131]:
```suggestion
        expect(ib.addresses.length).equals(3);
```

File: integration-tests/tests/src/tests/list.ts [hunk 2]
```diff
@@ -2126,13 +2130,23 @@ describe("Lists", () => {
...
       });
+
+      // update/replace one embedded child object
+      this.realm.write(() => {
+        ib.addresses[0] = { street: "Nørregade", city: "Vesterled" };
+      });
+
+      expect(3).equals(ib.addresses.length);
+      expect("Nørregade").equals(ib.addresses[0].street);
```
Comment (elle-j) [inline integration-tests/tests/src/tests/list.ts:2140]:
```suggestion
      expect(ib.addresses.length).equals(3);
      expect(ib.addresses[0].street).equals("Nørregade");
```

**Review by takameyer — APPROVED** [review]
Wow, good fix!
