### PR TITLE
Realm Web: Minor fixes

### LINKED ISSUE #2946: Realm Web: function not found: 'hasOwnProperty'
When console logging an `app.currentUser` the traversal of the objectgraph will call `hasOwnProperty` on the functions factory instance, yielding the following uncaught exception:
```
Request failed (POST https://stitch.mongodb.com/api/client/v2.0/app/movies-hajnm/functions/call): function not found: 'hasOwnProperty' (status 404 )
```

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

This closes #2946 by adding `Object.prototype`'s member functions as reserved function names.
It also adds a few minor changes to configuration files.

## ☑️ ToDos
* [x] 📝 Changelog entry
* [x] 📝 `Compatibility` label is updated or copied from previous entry
* [x] 🚦 Tests
* [x] 📝 Public documentation PR created or is not necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

**Comment by kraenhansen** [comment]
@steffenagger please review in retrospect.

File: packages/realm-web/src/FunctionsFactory.ts [hunk 1]
```diff
@@ -22,7 +22,12 @@ import { serialize } from "./utils/ejson";
 /**
  * A list of names that functions cannot have to be callable through the functions proxy.
  */
-const RESERVED_NAMES = ["inspect", "callFunction"];
+const RESERVED_NAMES = [
+    "inspect",
+    "callFunction",
+    // Methods defined on the Object.prototype might be "typeof probed" and called by libraries and runtime environments.
```
Comment (steffenagger) [inline packages/realm-web/src/FunctionsFactory.ts:28]: I don't think `typeof` is a function on `Object.prototype`,  would `valueOf` be a better example?
