### PR TITLE
Don't require optional or link properties when creating objects

### LINKED ISSUE #367: Missing property value for property name
Hi, I'm having problems with optional properties. When I mark property as optional and then I don't set it up on object being saved it throws exception
Unhandled JS Exception: Missing property value for property name

Here is the code I used for saving:
```javascript
'use strict';

import React, { Component, Text, View } from 'react-native';
import Realm from 'realm';

class Car {}
Car.schema = {
  name: 'Car',
  properties: {
    name: { type: 'string', optional: true },
    make: 'string',
    model: 'string'
  }
}
class TestRealm extends Component {
  render() {
    let realm = new Realm({schema: [Car]});
    let ferrari = new Car();
    ferrari.make = 'Ferrari';
    ferrari.model = 'Enzo';
    realm.write(() => {
      realm.create('Car', {
        make: 'Ferrari',
        model: 'Enzo'
      });
    });
    return (
      <View>
          <Text>Everything went better than expected</Text>
      </View>
    )
  }
}

export default TestRealm;
```

### PR DESCRIPTION
**Pull request by alazier**
Fixes #367 and #283 

@appden

### CODE REVIEW

File: src/object-store/src/object_accessor.hpp [hunk 1]
```diff
@@ -310,6 +312,9 @@ namespace realm {
                     if (Accessor::has_default_value_for_property(ctx, realm.get(), object_schema, prop.name)) {
                         object.set_property_value_impl(ctx, prop, Accessor::default_value_for_property(ctx, realm.get(), object_schema, prop.name), try_update);
                     }
+                    else if (prop.is_nullable || prop.type == PropertyTypeArray) {
+                        object.set_property_value_impl(ctx, prop, Accessor::null_value(ctx), try_update);
```
Comment (appden) [inline src/object-store/src/object_accessor.hpp]: I'm just curious, is it necessary to explicitly null these properties?

**Comment by appden** [comment]
Looks good :+1:
