### PR TITLE
Fix Timeout Error for Logged out User

### LINKED ISSUE #4453: When TimeOut behaviour is set to "openLocalRealm", error is thrown if user logs out before the timeout
### How frequently does the bug occur?

All the time

### Description

When TimeOut behaviour is set to "openLocalRealm", error is thrown if user logs out before the timeout.
If the timeout time is reached before logout, then there is no error.

### Stacktrace & log output

```shell
Error: User is no longer valid.
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:172:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
```
```


### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Open a realm containing the configuration:


```javascript
sync: {
  //...
    existingRealmFileBehavior: {
    type: "downloadBeforeOpen",
    timeOutBehavior: "openLocalRealm",
    timeOut: 30 * 1000 // arbitrary timeout value
  },
}
```

Perform a login and immediately logout.  After 30 seconds the error will appear.

### Version

10

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Node, macos

### Build environment

Which debugger for React Native: ..

### Cocoapods version

_No response_

### PR DESCRIPTION
**Pull request by takameyer**
## What, How & Why?

When opening Realm again with the same user and the timeOutBehaviour "openLocalRealm", logging the user out immediately would crash as the timeout event would try and open a local realm with the logged out user session.

This closes #4453

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [x] 🚦 Tests
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

File: tests/js/open-behavior-tests.js [hunk 1]
```diff
@@ -356,6 +356,70 @@ module.exports = {
     }
   },
 
+  testNewFile_downloadBeforeOpen_openLocalOnTimeOut_existing: async function () {
+    //This is a regression test.  If one were to logout before the openLocalRealm timeout
```
Comment (kneth) [inline tests/js/open-behavior-tests.js:360]: A like to the issue would be nice

**Review by kneth — APPROVED** [review]

File: lib/extensions.js [hunk 2]
```diff
@@ -228,6 +232,11 @@ module.exports = function (realmConstructor) {
                   asyncOpenTask.cancel();
                   asyncOpenTask = null;
                 }
+                // Resolve immediately if the other realm open promise has already finished
+                if (promiseResolved) {
+                  return resolve();
```
Comment (kraenhansen) [inline lib/extensions.js:237]: If anything it should reject, I don't like that it's resolving to `undefined`, if a bug gets introduced in the future this might make `Realm.open` return promises that doesn't resolve to a `Realm`: If anything it should `reject`.

File: tests/js/open-behavior-tests.js (hunk 1 above)
Comment (takameyer) [reply tests/js/open-behavior-tests.js:360]: I'll have to create one then.  Or should I link the help ticket directly?

File: lib/extensions.js (hunk 2 above)
Comment (takameyer) [reply lib/extensions.js:237]: I'm happy with rejecting

**Comment by kraenhansen** [comment]
I suggest an alternative fix where you `clearTimeout` of the timer returned here: https://github.com/realm/realm-js/blob/andrew/timeOutBehavior-fix/lib/extensions.js#L230

File: lib/extensions.js (hunk 2 above)
Comment (takameyer) [reply lib/extensions.js]: I've updated the code as per your suggestion using `clearTimeout`

File: lib/extensions.js [hunk 3]
```diff
@@ -197,6 +197,10 @@ module.exports = function (realmConstructor) {
 
         // First configure any timeOut and corresponding behavior.
         let openPromises = [];
+
+        // This will be set to true by the first promise to resolve.  The next promise will use this to stop execution
+        let fallbackTimeOutId = null;
```
Comment (kraenhansen) [inline lib/extensions.js:202]:
```suggestion
        // Id of the timer triggering the timeout
        let timeoutId = null;
```

There are no other timeout ids.

Comment (takameyer) [reply lib/extensions.js]: Good catch.  Fix is in

File: lib/extensions.js [hunk 4]
```diff
@@ -252,6 +256,10 @@ module.exports = function (realmConstructor) {
                 if (cancelled) {
                   return;
                 }
+                // Clear the fallback timeOut if it has been started
+                if (timeoutId) {
+                  clearTimeout(timeoutId);
+                }
```
Comment (kraenhansen) [inline lib/extensions.js:262]: In an ideal scenario I would love this to go into a `finally(() => { /
 ...*/ })` on the [`openPromise`](https://github.com/realm/realm-js/blob/andrew/timeOutBehavior-fix/lib/extensions.js#L274) - but let's save that for another PR 😄

**Review by kraenhansen — APPROVED** [review]

File: lib/extensions.js (hunk 4 above)
Comment (kraenhansen) [inline lib/extensions.js:262]: Calling this with `null` is actually okay: https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout#notes

```suggestion
                clearTimeout(timeoutId);
```

File: tests/js/open-behavior-tests.js (hunk 1 above)
Comment (takameyer) [reply tests/js/open-behavior-tests.js:360]: created https://github.com/realm/realm-js/issues/4453

File: tests/js/open-behavior-tests.js [hunk 5]
```diff
@@ -356,6 +356,70 @@ module.exports = {
...
+    //then the timeout would try to open a local realm with the timed out user
```
Comment (tomduncalf) [inline tests/js/open-behavior-tests.js:361]:
```suggestion
    // This is a regression test.  If one were to logout before the openLocalRealm timeout
    // then the timeout would try to open a local realm with the timed out user
```

File: tests/js/open-behavior-tests.js [hunk 6]
```diff
@@ -356,6 +356,70 @@ module.exports = {
...
+          user,
+          partitionValue,
+          _sessionStopPolicy: "immediately",
+        },
+      };
+
+      const realm = await Realm.open(config);
+
+      console.log(realm.path);
+
```
Comment (tomduncalf) [inline tests/js/open-behavior-tests.js:388]:
```suggestion
```

**Review by tomduncalf — APPROVED** [review]

File: tests/js/open-behavior-tests.js (hunk 6 above)
Comment (takameyer) [reply tests/js/open-behavior-tests.js:388]: doooh!

File: lib/extensions.js (hunk 4 above)
Comment (takameyer) [reply lib/extensions.js]: Sounds good.  Someday we should just rewrite this entirely.  I'm also kind of unhappy about `timeOut` vs `timeout`.  Maybe a breaking change ticket is in order

File: tests/js/open-behavior-tests.js [hunk 7]
```diff
@@ -356,6 +356,68 @@ module.exports = {
...
+          partitionValue,
+          _sessionStopPolicy: "immediately",
+          existingRealmFileBehavior: {
+            type: "downloadBeforeOpen",
+            timeOut: 1000,
+            timeOutBehavior: "openLocalRealm",
+          },
+        },
+      };
+      await Realm.open(config);
```
Comment (kraenhansen) [inline tests/js/open-behavior-tests.js:412]: As you're awaiting the promise returned by realm.open before you log out, why would this trigger the original bug?
Did this throw before you did the fix?
