### PR TITLE
Checking the content-type of authentication responses

### LINKED ISSUE #1555: "Unexpected token < in JSON at position 0" when connecting to a broken ROS
## Goals

I want a better error message when issuing an /auth request to a broken instance of ROS.

## Expected Results

An error with the following message:

> Could not authenticate: Realm Object Server didn't respond with valid JSON.

## Actual Results

I get a syntax error with this message:

> Unexpected token d in JSON at position 0

## Steps to Reproduce

Try to authenticate with a ROS instance that does not have the auth service started or to any server that does not implement the ROS protocol.

## Code Sample

    const Realm = require('realm');
    Realm.Sync.User.login('http://realm.io', 'user', 'password').then(console.log, console.error);

outpus this on node.js:

> { FetchError: invalid json response body at https://realm.io/404?domain=realm.io&path=%2Fauth reason: Unexpected token < in JSON at position 0
    at /Users/kraenhansen/Repositories/realm-studio/node_modules/node-fetch/lib/body.js:48:31
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  name: 'FetchError',
  message: 'invalid json response body at https://realm.io/404?domain=realm.io&path=%2Fauth reason: Unexpected token < in JSON at position 0', type: 'invalid-json' }

And this from an Electron renderer process:

> SyntaxError: Unexpected token < in JSON at position 0

Ideally Realm JS should check if the response from the server has the expected content-type before parsing it as JSON (here https://github.com/realm/realm-js/blob/master/lib/user-methods.js#L157-L159):

    if (response.headers.get('Content-Type') !== 'application/json') {
      return response.text().then((body) => {
        throw new AuthError({
          title: `Could not authenticate: Realm Object Server didn't respond with valid JSON`,
          body,
        });
      });
    } else if (!response.ok) {
      return response.json().then((body) => Promise.reject(new AuthError(body)));
    } else {
      // ...
    }

## Version of Realm and Tooling

- Realm JS SDK Version: 2.0.11
- Node or React Native: Both
- Client OS & Version: Mac
- Which debugger for React Native: N/A

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

This closes #1555 and https://github.com/realm/realm-studio/issues/417

## ☑️ ToDos

* [x] 📝 Changelog entry
* [x] 🚦 Tests
* [x] 📝 Public documentation PR created or is not necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

File: tests/js/user-tests.js [hunk 1]
```diff
@@ -160,6 +160,20 @@ module.exports = {
       .catch((e) => assertIsError(e));
   },
 
+  testLoginTowardsMisbehavingServcer() {
```
Comment (fealebenpae) [inline tests/js/user-tests.js]: typo in `Servcer`.
