### PR TITLE
Fix setting an object with an embedded object property to `null` 

### LINKED ISSUE #6280: Nullable embedded schema behaves differently on Realm 12 and 11
### How frequently does the bug occur?

Always

### Description

Realm 11.9.0 and 12.3.1 (I suppose it since 12.0.0) have different behavior when setting the embedded object field to null. 
While 11.9.0 allows us to do it, 12.3.1 doesn't set null to an object field. Will it be fixed, or are these new validation constraints?

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Always

### Reproduction Steps

I've created an example to show the difference between Realm 12.3.1 and 11.9.0.

https://github.com/andreyukD/reproduce-realmjs-issue (branch v12-3-1)

Starting point was `npx create-expo-app MyAwesomeRealmApp --template @realm/expo-template`

I've added a new field `items` in `Task` schema

commit with 12.3.1 - https://github.com/andreyukD/reproduce-realmjs-issue/commit/82700701cccf2f794e912fb99a7a8466d4092767
commit with 11.9.0 - https://github.com/andreyukD/reproduce-realmjs-issue/commit/b1ce35065b97c24b32dc9c6f7c55dc46b25ddef6

https://github.com/realm/realm-js/assets/33383393/45beff07-7b8c-42d1-b662-9adef282d636

https://github.com/realm/realm-js/assets/33383393/5a337bc3-9be8-4374-a3c2-680a6c42fc8d

### Version

12.3.1 / 11.9.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

macOS 14.0

### Build environment

Which debugger for React Native: ..

### Cocoapods version

_No response_

### PR DESCRIPTION
**Pull request by elle-j**
## What, How & Why?

Updating an object's property whose value was an embedded object did not call into Core to update the underlying object when the new value was `null` or `undefined`.

This closes #6280 

## ☑️ ToDos
* [x] 📝 Changelog entry
* [x] 🚦 Tests

### CODE REVIEW

**Review by kneth — APPROVED** [review]

File: integration-tests/tests/src/tests/objects.ts [hunk 1]
```diff
@@ -1253,6 +1277,43 @@ describe("Realm.Object", () => {
     });
   });
 
+  describe("embedded properties", () => {
+    openRealmBeforeEach({ schema: [EmbeddedObjectSchema, ObjectWithEmbeddedObjectSchema] });
+
+    it("sets an embedded property to null", function (this: Mocha.Context & RealmContext) {
+      this.realm.write(() => {
+        this.realm.create(ObjectWithEmbeddedObjectSchema.name, { embeddedValue: null });
```
Comment (kraenhansen) [inline integration-tests/tests/src/tests/objects.ts:1285]: Should we test the different update modes too?
