### PR TITLE
Fix realm open android debugger

### LINKED ISSUE #1248: Realm.open() hangs on Android
EDIT: This also happens after reloading the emulator on React Native, in a very simple setup (see below https://github.com/realm/realm-js/issues/1248#issuecomment-328313637)

## Goals

Get an error message when opening a synced realm if server not available or user is offline.

## Expected Results

Realm.open() returns a promise that gets rejected with useful error message.

## Actual Results

The promise simply stays in pending status indefinitely.

This callback does not get called:

https://github.com/realm/realm-js/blob/416632c9adc7350cdca12dc792edcf3e9d0b30d8/lib/extensions.js#L47

Hence the promise never returns.

## Steps to Reproduce

Run this code after log in with valid user:

```
const openRealm = (user, url, schema) => {
  return Realm.open({
    sync: { user, url },
    schema,
    schemaVersion: 1
  });
};

```

## Version of Realm and Tooling

- Realm JS SDK Version: 1.10.3
- React Native: 0.44.3
- Which debugger for React Native: None

### PR DESCRIPTION
**Pull request by blagoev**
this fixes #1248 #1369 and allows the debugger to work with arbitrary async callbacks

### CODE REVIEW

File: lib/browser/rpc.js [hunk 1]
```diff
@@ -230,17 +231,19 @@ function deserialize_json_value(value) {
...
+        
+        let url = 'http://' + host + '/' + command;
+        let response = makeRequest(url, data);
 
-    if (!response || response.error) {
-        let error = response && response.error;
+        if (!response || response.error) {
+            let error = response && response.error;
 
         // Remove the type prefix from the error message (e.g. "Error: ").
```
Comment (kneth) [inline lib/browser/rpc.js]: Indentation seems to be wrong.

**Comment by kneth** [comment]
@blagoev Please remember to update `CHANGELOG.md`.
