### PR TITLE
Sync.flexible and deleteRealmIfMigrationNeeded is not an allowed combination

### LINKED ISSUE #5548: [v11] Don't mix `deleteRealmIfMigrationNeeded` and sync
### How frequently does the bug occur?

Always

### Description

Deleting a Realm file due to migration will lead to crashes if sync is enabled

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Always

### Reproduction Steps

_No response_

### Version

11.5.0

### What services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

Any

### Build environment

Which debugger for React Native: ..

### Cocoapods version

_No response_

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

This closes #5548 

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [x] 🚦 Tests
* [ ] 🔀 Executed flexible sync tests locally if modifying flexible sync
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated

### CODE REVIEW

File: src/js_realm.hpp [hunk 1]
```diff
@@ -32,6 +32,7 @@
 #include "realm/binary_data.hpp"
 #include "realm/util/functional.hpp"
 #include <exception>
+#include <iostream>
```
Comment (takameyer) [inline src/js_realm.hpp:35]: Why was `iostream` included in this change?

**Review by takameyer — APPROVED** [review]
LGTM :shipit:

File: src/js_realm.hpp (hunk 1 above)
Comment (kneth) [reply src/js_realm.hpp:35]: Left-over from debugging - I'll remove it
