### PR TITLE
Android RN should use same cache clearing logic as iOS

### LINKED ISSUE #3668: App login function freezes/hangs when React-Native environment is reloaded (press R twice) on Android
## Goals

Fix freezing login function on App class in React-Native Android application after reloading.

## Expected Results

Login function should not freeze.

## Actual Results

Login function freezes/hangs forever after logging in into application when the application is reloaded.

## Steps to Reproduce

We have a React-Native application running as Android application (in emulator, but similar thing happens on real device). When I reload the application in React-Native environment (pressing R key twice) and I try to log in then the application will freeze forever on login function in App class.

What I already tried:
- `realmApp.allUsers[key].loggedIn` - false (only one user visible in allUsers)
- `realmApp.allUsers[key].logOut()` - didn't help
- `realmApp.currentUser` = returns null
- deleting realm files with adb shell commands - didn't help
- killing the application from memory - after starting the application it works again (just by closing where the application is running in the background and starting it from there doesn't help)
- reinstalling the application (`react-native run-android`) - works again

## Code Sample

```
const getRealmApp = () => {
  const appConfig = {
    id: Config.REALM_DIR,
    timeout: 30000,
  };
  return new Realm.App(appConfig);
};

export const realmApp = getRealmApp();



export const signIn = async jwt => {
  const creds = Realm.Credentials.jwt(jwt);
  await realmApp?.logIn(creds);  // <- the application will hang on this line
};
```

## Version of Realm and Tooling

- Realm npm package: 10.2.0
- Realm JS SDK Version: ?
- react-native: 0.63.3
- Android: 10
- node: v14.9.0
- Which debugger for React Native: 0.10.7 (not connected)

### PR DESCRIPTION
**Pull request by RedBeard0531**
## What, How & Why?

This makes it also call `realm::app::App::clear_cached_apps()`, which
fixes #3668. This also makes it more maintainable by having a single place to
put all cache clearing logic for all RN platforms.

This PR replaces and closes #3755.

## ☑️ ToDos

* [x] 📝 Changelog entry
* ~[ ] 📝 `Compatibility` label is updated or copied from previous entry~
* ~[ ] 🚦 Tests~
* ~[ ] 📝 Public documentation PR created or is not necessary~
* ~[ ] 💥 `Breaking` label has been applied or is not necessary~

<del>
*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native
</del>

### CODE REVIEW

File: src/android/jsc_override.cpp [hunk 1]
```diff
@@ -134,7 +134,7 @@ static JSGlobalContextRef create_context(JSContextGroupRef group, JSClassRef glo
     swap_function();
 
     // Clear cache from previous instances.
-    realm::_impl::RealmCoordinator::clear_all_caches();
+    RJSInvalidateCaches();
```
Comment (RedBeard0531) [inline src/android/jsc_override.cpp:137]: For reference, here is this function: https://github.com/realm/realm-js/blob/5b0eabf940d843b76835b6e889817f4052c0b5c3/src/jsc/jsc_init.cpp#L57-L62

**Review by kneth — APPROVED** [review]

**Review by kraenhansen — APPROVED** [review]
