### PR TITLE
Validate configuration

### LINKED ISSUE #3771: Disallow in-memory for sync Realms
If `inMemory` is set to true for a synced Realm, the fatal error `terminating with uncaught exception of type realm::LogicError: Durability setting (as passed to the SharedGroup constructor) was not consistent across the session` can be observed.

In general, it is not possible to sync a Realm to memory only, and Realm Core assumes that the app developer is aware of this.

It is a bug that Realm JavaScript isn't validating the Realm configuration and terminates early so the app developer becomes aware of it.

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

This closes #3771 

## ☑️ ToDos
* [x] 📝 Changelog entry
* ~[ ] 📝 `Compatibility` label is updated or copied from previous entry~
* [x] 🚦 Tests
* ~[ ] 📝 Public documentation PR created or is not necessary~
* ~[ ] 💥 `Breaking` label has been applied or is not necessary~

*If this PR adds or changes public API's:*
* [x] typescript definitions file is updated
* ~[ ] jsdoc files updated~
* ~[ ] Chrome debug API is updated if API is available on React Native~

### CODE REVIEW

**Review by fronck — APPROVED** [review]

**Review by nirinchev — CHANGES_REQUESTED** [review]
Is `disableFormatUpgrade` an option compatible with sync? I would imagine that this would prevent Sync from writing to the file. Additionally, we should express these incompatibilities in the typescript definitions so that people who are using an editor that respects ts definitions will get early feedback if they try to construct an invalid config.

**Review by nirinchev — APPROVED** [review]

File: types/index.d.ts [hunk 1]
```diff
@@ -107,25 +107,38 @@ declare namespace Realm {
...
+    interface ConfigurationWithSync extends BaseConfiguration {
+        sync: SyncConfiguration,
+        migration?: never,
+        inMemory?: never,
+        deleteRealmIfMigrationNeeded?: never,
+        disableFormatUpgrade?: never
+    }
+
+    interface ConfigurationWithoutSync extends BaseConfiguration {
+        sync?: never,
```
Comment (takameyer) [inline types/index.d.ts:129]:
```suggestion
        sync: SyncConfiguration;
        migration?: never;
        inMemory?: never;
        deleteRealmIfMigrationNeeded?: never;
        disableFormatUpgrade?: never;
    }

    interface ConfigurationWithoutSync extends BaseConfiguration {
        sync?: never;
```
The interface properties should end in `;`

**Review by takameyer — CHANGES_REQUESTED** [review]
Just a formatting issue that should be addressed.

I am not completely satisfied with how the typings resolve for configuration, but I have no alternative solution at the moment.  If the developer explicitly uses `ConfigurationWithSync`, then the TS errors look nice, but if they use the `Configuration` union, the TS errors are quite vague.  If I come up with a better solution later, I will make a separate PR.

Otherwise, LGTM

**Review by takameyer — APPROVED** [review]
