### PR TITLE
Fixing chrome debugging on v10

### LINKED ISSUE #3358: Enabling React Native Debug mode causes Error: Must first create RPC session with a valid host from rpc.js:314
## Goals
Enable React Native **Debug** mode in order to troubleshoot console errors, set breakpoints, profile app, and monitor network requests.

## Expected Results
Mobile app connects to React Native Debugger successfully and I'm able to set breakpoints,  profile app, and monitor network requests, view console errors

## Actual Results
* Mobile App crashes with the following error

> Error: Must first create RPC session with a valid host from rpc.js:314

:19

Mobile App

### Sentry Stacktrace
```jsx
Error: Must first create RPC session with a valid host
  File "app:///rpc.js", col 18, in sendRequest
  File "app:///rpc.js", col 41, in setTimeout$argument_0
  File "app:///JSTimers.js", col 17, in _allocateCallback$argument_0
  File "app:///JSTimers.js", col 6, in _callTimer
  File "app:///JSTimers.js", col 6, in callTimers
  at <unknown>(app:///RNDebuggerWorker.js:2:134503)
```

## Steps to Reproduce

1. Run `yarn android` to build react native application and install on device
1. Shake device to reveal developer menu and select `Debug` . This is successful if the user is not logged in

   image

1. Login to account which causes realm database to be initialized
1. An exception occurs on mobile app

```
![https://user-images.githubusercontent.com/222459/96701643-bea69400-1388-11eb-911e-9ee8323b2795.png](https://user-images.githubusercontent.com/222459/96701643-bea69400-1388-11eb-911e-9ee8323b2795.png)
```

    The crash occurs when the following is called **`Realm.schemaVersion(Realm.defaultPath)`**     **`Realm.defaultPath`** displays an error when inspected using React Native debugger. See video below```
  image
```

## Code Sample
<!---
Please provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Full projects that we can compile and run ourselves are ideal!
-->

```jsx
export const runMigration = ({currentSchema}: {currentSchema: any}) => {
  if (!schemas.length) {
    return {schemaVersion: 0};
  }

  **let nextSchemaIndex = Realm.schemaVersion(Realm.defaultPath);**
  schemas[schemas.length - 1].schema = currentSchema;

  // If -1, it means this is a new Realm file, so no migration is needed
  if (nextSchemaIndex !== -1) {
    while (nextSchemaIndex < schemas.length) {
      const migratedRealm = new Realm(schemas[nextSchemaIndex++]);
      migratedRealm.close();
    }
  }

  return {schemaVersion: schemas[schemas.length - 1].schemaVersion};
};
```

## Version of Realm and Tooling
* Realm JS SDK Version: 10.0.1
* Node or React Native: 0.63.3
* Client OS & Version: OnePlus 6 A6003, Android 10
* Which debugger for React Native: React Native Debugger

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

This closes #3358 and #3361 by
1. Fixing the implementation of the RPC stub for `App`
2. Introducing a `RPCNetworkTransport` implementation of the `GenericNetworkTransport` provided by object store. This struct is statically provided a function (assigned by the `RPCServer` when a session gets created), which calls back into the browser to execute fetch requests, ultimately on behalf of object store.
3. Bonus: Introduced a better serialization+deserialization of `Error` instances to propagate the stack when an error is thrown during an RPC call.

## ☑️ ToDos
* [x] 📝 Changelog entry
* [x] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [x] 📝 Public documentation PR created or is not necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

**Comment by Anzormumladze** [comment]
are fucking kidding me ?

**Comment by kraenhansen** [comment]
> are fucking kidding me ?

What more specifically are you referring to?

**Comment by Anzormumladze** [comment]
> > are fucking kidding me ?
> 
> Most likely not ...
> What more specifically are you referring to?

we are waiting for this fix for 3 years.......

**Comment by kraenhansen** [comment]
> we are waiting for this fix for 3 years.......

Most likely not, the issues I'm fixing with this PR was introduced with Realm JS v10.0.0, which was released 14th of October, so its been more like a month (which I agree is also a long wait). I suspect you're looking for a fix to an issue that might not have been identified if you've been waiting 3 years - have you created an issue on GitHub that you can link to?

**Comment by Anzormumladze** [comment]
> > we are waiting for this fix for 3 years.......
> 
> Most likely not, since the issues I'm fixing with this PR was introduced with Realm JS v10.0.0, which was released 14th of October. So it has been more like a month (which I agree is also a long wait). I suspect you're looking for a fix to an issue that might not have been identified if you've been waiting 3 years - have you created an issue on GitHub that you can link to?

https://stackoverflow.com/questions/44016885/error-after-installing-realm-must-first-create-rpc-session-with-a-valid-host

**Comment by kraenhansen** [comment]
> https://stackoverflow.com/questions/44016885/error-after-installing-realm-must-first-create-rpc-session-with-a-valid-host

This is a post on stackoverflow and not an issue here on GitHub.
It's referring to Realm JS v1.3.0 which was released more than three years ago. If you're still using v1.3.0, I would highly recommend upgrading to the latest version (v6 for now, if you're heavily relying on the remote chrome debugger).

**Comment by Anzormumladze** [comment]
> > https://stackoverflow.com/questions/44016885/error-after-installing-realm-must-first-create-rpc-session-with-a-valid-host
> 
> This is a post on stackoverflow and not an issue here on GitHub.
> It's referring to Realm JS v1.3.0 which was released more than three years ago. If you're still using v1.3.0, I would highly recommend upgrading to the latest version (v6 for now, if you're heavily relying on the remote chrome debugger).

dude why you arguing with me, this issue exists on every version of realm js, go code something

**Comment by geragray** [comment]
@Anzormumladze I understand your frustration when it comes to debugging with JS SDK. You are right, this is a well know issue (explained in detail here https://github.com/realm/realm-js/issues/491). We are hoping to fix it by investing in https://github.com/realm/realm-js/issues/2455. Please subscribe. 

I would also like to point out that leaving derogatory comments is against our code of conduct https://realm.io/conduct/. Please refrain from using foul language in the future.

**Comment by kevinrodriguez-io** [comment]
@kraenhansen You're doing an amazing work to get this out. Tell me if I can help with something, looking forward to fix this issue for our developer team.

**Comment by Anzormumladze** [comment]
> @Anzormumladze I understand your frustration when it comes to debugging with JS SDK. You are right, this is a well know issue (explained in detail here #491). We are hoping to fix it by investing in #2455. Please subscribe.
> 
> I would also like to point out that leaving derogatory comments is against our code of conduct https://realm.io/conduct/. Please refrain from using foul language in the future.

thanks for answering me back, I deleted all my comment and looking forward to seeing good news

File: lib/browser/rpc.js [hunk 1]
```diff
@@ -366,14 +382,14 @@ function sendRequest(command, data, host = sessionHost) {
                     error = `Unknown callback id: ${callback}`
                 }
             } catch (e) {
-                error = e.message || ('' + e);
+                error = e.message || ("" + e);
```
Comment (kneth) [inline lib/browser/rpc.js:385]:
```suggestion
                error = e.message || (`${e}`);
```

File: src/js_app.hpp [hunk 2]
```diff
@@ -160,18 +171,23 @@ void AppClass<T>::constructor(ContextType ctx, ObjectType this_object, Arguments
...
 
-    auto realm_constructor = js::Value<T>::validated_to_object(ctx, js::Object<T>::get_global(ctx, "Realm"));
     std::string user_agent_binding_info;
     auto user_agent_function = js::Object<T>::get_property(ctx, realm_constructor, "_createUserAgentDescription");
     if (js::Value<T>::is_function(ctx, user_agent_function)) {
         auto result = js::Function<T>::call(ctx, js::Value<T>::to_function(ctx, user_agent_function), realm_constructor, 0, nullptr);
         user_agent_binding_info = js::Value<T>::validated_to_string(ctx, result);
     }
+    else {
+        // FIXME: When debugging RN apps, _createUserAgentDescription cannot be found
```
Comment (kneth) [inline src/js_app.hpp:188]: We will have to create a callback to the browser to get it to work. On the other hand, while debugging, it is not so important.

File: src/js_app.hpp [hunk 3]
```diff
@@ -160,18 +171,23 @@ void AppClass<T>::constructor(ContextType ctx, ObjectType this_object, Arguments
...
+        user_agent_binding_info = "N/A";
```
Comment (kneth) [inline src/js_app.hpp:189]:
```suggestion
        user_agent_binding_info = "RN debugging";
```

File: src/js_app.hpp [hunk 4]
```diff
@@ -185,6 +201,12 @@ void AppClass<T>::constructor(ContextType ctx, ObjectType this_object, Arguments
         config.platform_version = js::Value<T>::validated_to_string(ctx, Object::get_property(ctx, result_object, platform_version_name));
         config.sdk_version = js::Value<T>::validated_to_string(ctx, Object::get_property(ctx, result_object, sdk_version_name));
     }
+    else {
+        // FIXME: When debugging RN apps, _createPlatformDescription() cannot be found
+        config.platform = "N/A";
```
Comment (kneth) [inline src/js_app.hpp:206]:
```suggestion
        config.platform = "RN debugging";
```

File: src/js_app_credentials.hpp [hunk 5]
```diff
@@ -63,6 +63,12 @@ class CredentialsClass : public ClassDefinition<T, realm::app::AppCredentials> {
         {"serverApiKey",     wrap<server_api_key>},
         {"jwt",              wrap<jwt>},
     };
+    
+    static void get_payload(ContextType, ObjectType, ReturnValue &);
+    
+    PropertyMap<T> const properties = {
+        {"payload", {wrap<get_payload>, nullptr}},
```
Comment (kneth) [inline src/js_app_credentials.hpp:70]: Should it be added to the API doc and TS defs?

**Review by kneth — COMMENTED** [review]
I think you need to add the new network transport to `Android.mk`.

File: lib/browser/rpc.js (hunk 1 above)
Comment (kraenhansen) [reply lib/browser/rpc.js:385]: This was an automatic change from applying the eslint rules of the project root folder. I would rather not spent too much time on editing this any futher :)

File: src/js_app.hpp (hunk 2 above)
Comment (kraenhansen) [reply src/js_app.hpp:188]: That's a great point - I overlooked this.

File: src/js_app_credentials.hpp (hunk 5 above)
Comment (kraenhansen) [reply src/js_app_credentials.hpp:70]: Great catch. It's [already in the TS defs](https://github.com/realm/realm-js/blob/master/types/app.d.ts#L135) and I'll add it to the API docs.

**Comment by kraenhansen** [comment]
> I think you need to add the new network transport to Android.mk.

If that was the case, I'm wondering why the integration tests are passing?

I think it doesn't have to be added since it's a header and those are taken care of on a pr directory level here: https://github.com/realm/realm-js/blob/master/react-native/android/src/main/jni/Android.mk#L95

File: src/js_app.hpp (hunk 4 above)
Comment (kraenhansen) [reply src/js_app.hpp:206]: For context, this was how the previous react native SDK reported its platform:

https://github.com/mongodb/stitch-js-sdk/blob/310f0bd5af80f818cdfbc3caf1ae29ffa8e9c7cf/packages/react-native/core/src/core/auth/internal/StitchAuthImpl.ts#L141-L143

File: src/rpc.cpp [hunk 6]
```diff
@@ -484,7 +527,9 @@ RPCServer::RPCServer() {
         }
 
         JSObjectRef credentials_object = (JSObjectRef)jsc::Function::call(m_context, email_password_method, arg_count, arg_values);
-        return (json){{"result", serialize_json_value(credentials_object)}};
+        
+        auto serialized_result = serialize_json_value(credentials_object);
```
Comment (blagoev) [inline src/rpc.cpp:531]: consider `auto&` or reverting this change

File: src/js_app.hpp (hunk 3 above)
Comment (kraenhansen) [reply src/js_app.hpp]: I understand that this would be the case from a practical level, but if we had a bug in our extension code the `_createUserAgentDescription` method might not be assigned and then I think it's misleading to send "RN debugging".

File: src/js_app.hpp (hunk 4 above)
Comment (kraenhansen) [reply src/js_app.hpp]: Same as [the other comment ](https://github.com/realm/realm-js/pull/3411#discussion_r529467419). I would suggest setting this to `"js-unknown"` to follow the pattern used by the legacy SDK and at the same time signal that the platform isn't known at this point. It'll most likely be react native chrome debugging, but we're checking for the existence of a function and not actually that we're running in that environment.

File: lib/browser/rpc.js [hunk 7]
```diff
@@ -90,74 +107,74 @@ export function asyncOpenRealm(id, config, callback) {
...
 export function callSyncFunction(name, args) {
     args = (args || []).map((arg) => serialize(null, arg));
-    let result = sendRequest('call_sync_function', { name, arguments: args });
+    let result = sendRequest("call_sync_function", { name, arguments: args });
     return deserialize(undefined, result);
 }
 
 export function callMethod(realmId, id, name, args) {
-    if (args) {
+    if (args && Array.isArray(args)) {
```
Comment (blagoev) [inline lib/browser/rpc.js:168]: this should be a argument validation instead of silencing the error

File: lib/browser/rpc.js (hunk 1 above)
Comment (blagoev) [reply lib/browser/rpc.js:385]: well there is the `commit suggestion` button :)

File: src/js_app.hpp [hunk 8]
```diff
@@ -160,18 +171,23 @@ void AppClass<T>::constructor(ContextType ctx, ObjectType this_object, Arguments
         throw std::runtime_error("Expected either a configuration object or an app id string.");
     }
 
-    Protected<typename T::GlobalContext> protected_ctx(Context<T>::get_global_context(ctx));
-    config.transport_generator = [=] {
-        return std::make_unique<NetworkTransport>(protected_ctx);
+    auto realm_constructor = js::Value<T>::validated_to_object(ctx, js::Object<T>::get_global(ctx, "Realm"));
+    
+    Protected<typename T::GlobalContext> protected_ctx(Context::get_global_context(ctx));
+    config.transport_generator = [protected_ctx] {
```
Comment (blagoev) [inline src/js_app.hpp:177]: We should be using this syntax everywhere we have to protect the context 
https://github.com/realm/realm-js/blob/master/src/js_types.hpp#L708
this helps with making sure we don't introduce unintentional bugs cause of the two ctx names existing in the same scope

File: src/js_app.hpp [hunk 9]
```diff
@@ -160,18 +171,23 @@ void AppClass<T>::constructor(ContextType ctx, ObjectType this_object, Arguments
...
 
-    auto realm_constructor = js::Value<T>::validated_to_object(ctx, js::Object<T>::get_global(ctx, "Realm"));
     std::string user_agent_binding_info;
     auto user_agent_function = js::Object<T>::get_property(ctx, realm_constructor, "_createUserAgentDescription");
     if (js::Value<T>::is_function(ctx, user_agent_function)) {
         auto result = js::Function<T>::call(ctx, js::Value<T>::to_function(ctx, user_agent_function), realm_constructor, 0, nullptr);
         user_agent_binding_info = js::Value<T>::validated_to_string(ctx, result);
     }
+    else {
+        // The `_createUserAgentDescription` method is undefined when chrome debugging a React Native app
```
Comment (blagoev) [inline src/js_app.hpp:188]: this function needs to accommodate that it might get executed in RN environment and we should call it here

File: src/jsc/jsc_rpc_network_transport.hpp [hunk 10]
```diff
@@ -0,0 +1,71 @@
...
+namespace rpc {
+
+/*
+struct RPCFetchRef {
+    static JSValueRef value;
+};
+*/
+
+/**
+ * Provides an implementation of GenericNetworkTransport for use when the library is loaded in a runtime which doesn't provide the APIs required to perform network requests directly.
```
Comment (blagoev) [inline src/jsc/jsc_rpc_network_transport.hpp:36]: I don't see the need to implement this. we should be able to use the JSNetworkTransport.

File: src/js_types.hpp [hunk 11]
```diff
@@ -126,6 +126,7 @@ struct Value {
     static bool is_boolean(ContextType, const ValueType &);
     static bool is_constructor(ContextType, const ValueType &);
     static bool is_date(ContextType, const ValueType &);
+    static bool is_error(ContextType, const ValueType &);
```
Comment (blagoev) [inline src/js_types.hpp:129]: whenever we change the abstraction layer we need to handle it both for Nodejs and RN

File: src/jsc/jsc_value.hpp [hunk 12]
```diff
@@ -85,6 +85,12 @@ inline bool jsc::Value::is_constructor(JSContextRef ctx, const JSValueRef &value
     return JSValueIsObject(ctx, value) && JSObjectIsConstructor(ctx, (JSObjectRef)value);
 }
 
+template<>
+inline bool jsc::Value::is_error(JSContextRef ctx, const JSValueRef &value) {
```
Comment (blagoev) [inline src/jsc/jsc_value.hpp:89]: whenever we change the abstraction layer we need to handle it both for Nodejs and RN

**Review by blagoev — CHANGES_REQUESTED** [review]

File: src/js_app.hpp (hunk 3 above)
Comment (nirinchev) [reply src/js_app.hpp]: I think it's a bit pessimistic to optimize for the case where we have bugs in our code. We should instead assume that the code works as intended and provide the most relevant UX to users.

Comment (kraenhansen) [reply src/js_app.hpp]: > I think it's a bit pessimistic to optimize for the case where we have bugs in our code.

I disagree.

The suggested change is too specific to the situations that might be causing the function to be undefined. In my opinion, the "right" solution would be to provide an authoritative runtime check which determines is we're running in the chrome debugger mode, but I honestly see very little value in that, since these values likely wont be relevant to the developer through the MongoDB Realm admin dashboard.

File: src/RealmJS.xcodeproj/project.pbxproj [hunk 13]
```diff
@@ -727,6 +728,7 @@
 		F6874A441CAD2ACD00EEEE36 /* JSC */ = {
 			isa = PBXGroup;
 			children = (
+				DC0FCC4C256817E80028429B /* jsc_rpc_network_transport.hpp */,
```
[the remark this answers is not in the document]
Comment (kraenhansen) [reply src/RealmJS.xcodeproj/project.pbxproj:731]: As [I wrote @kneth above](https://github.com/realm/realm-js/pull/3411#issuecomment-732062134), this is a header file and I therefore don't think that's needed.

File: src/rpc.cpp [hunk 14]
```diff
@@ -248,6 +259,23 @@ RPCServer::RPCServer() {
         setIncludesNativeCallStack(m_context, false);
     }
 
+    m_requests["/create_session"] = [this](const json dict) {
+        RJSInitializeInContext(m_context);
```
[the remark this answers is not in the document]
Comment (kraenhansen) [reply src/rpc.cpp:263]: I honestly don't know, this is simply copying in the implementation that got removed by accident, from https://github.com/realm/realm-js/blob/v6/src/rpc.cpp#L252-L265.

File: src/jsc/jsc_value.hpp (hunk 12 above)
Comment (kraenhansen) [reply src/jsc/jsc_value.hpp:89]: Thanks for catching this - I thought about it and forgot about it :)

File: src/js_app.hpp [hunk 15]
```diff
@@ -36,12 +36,16 @@ using SharedUser = std::shared_ptr<realm::SyncUser>;
...
+template<typename T>
+using NetworkTransportFactory = std::function<std::unique_ptr<app::GenericNetworkTransport>(typename T::Context)>;
+
 template<typename T>
 class AppClass : public ClassDefinition<T, SharedApp> {
     using ContextType = typename T::Context;
     using FunctionType = typename T::Function;
     using ObjectType = typename T::Object;
     using ValueType = typename T::Value;
+    using Context = js::Context<T>;
```
[the remark this answers is not in the document]
Comment (kraenhansen) [reply src/js_app.hpp:48]: It's used here https://github.com/realm/realm-js/blob/kh/rn-create-session-continued/src/js_app.hpp#L176

File: src/rpc.cpp (hunk 6 above)
Comment (kraenhansen) [reply src/rpc.cpp:531]: Is this to prevent a (potentially expensive) move?

Comment (kraenhansen) [reply src/rpc.cpp:531]: I'll revert, this was added while debugging.

File: src/js_app.hpp (hunk 9 above)
Comment (kraenhansen) [reply src/js_app.hpp:188]: I don't understand this comment ☝️  Can I get you to rephrase it?

File: src/jsc/jsc_rpc_network_transport.hpp (hunk 10 above)
Comment (kraenhansen) [reply src/jsc/jsc_rpc_network_transport.hpp:36]: Can you provide an explanation to this? What makes you think it would be better to use the `JSNetworkTransport`? That is basically just a wrapper around some JavaScript code which won't be loaded in the case of us running in chrome debugger mode. I see no advantage in trying to polyfill the `_networkTransport` property from C++.

File: lib/browser/rpc.js (hunk 1 above)
Comment (kneth) [reply lib/browser/rpc.js:385]: Just leave as it is - `"" + e` is just so much last year :smile:

File: src/js_app.hpp (hunk 9 above)
Comment (kneth) [reply src/js_app.hpp:187]: In the past, a sync session should be opened without setting `user_agent_binding_info` so we silently skipped the call when the RN debugger was active: https://github.com/realm/realm-js/blob/v6/src/js_sync.hpp#L62-L65

File: src/js_app.hpp (hunk 3 above)
Comment (nirinchev) [reply src/js_app.hpp]: I agree that an unambiguous check if the code is running in a debugger is better, but don't agree with the rest. I don't think a user will easily make the connection that "js-unknown" means a debugger, so is likely to be left with the impression that either our code or theirs is broken and doesn't correctly report the platform.

If this function is only unrefined in a debugger, then using that as a check, even if semantically incorrect, is better than providing a broken user experience.

Comment (kneth) [reply src/js_app.hpp]: In pre-v10 we skipped setting it as object store didn't require it. With v10, it is now a requirement. You can say that we are doing more or less the same as before.

**Review by kneth — APPROVED** [review]

File: src/RealmJS.xcodeproj/project.pbxproj (hunk 13 above)
[the remark this answers is not in the document]
Comment (blagoev) [reply src/RealmJS.xcodeproj/project.pbxproj:731]: oh its a `hpp`. its alright then

File: lib/browser/rpc.js (hunk 1 above)
Comment (blagoev) [reply lib/browser/rpc.js:385]: seriously, why not click the `commit suggestion` button

File: src/rpc.cpp (hunk 14 above)
[the remark this answers is not in the document]
Comment (blagoev) [reply src/rpc.cpp:263]: I see. I was comparing against the previous version. If this was removed in v10 then it was a big accident indeed

File: lib/browser/rpc.js [hunk 16]
```diff
@@ -334,20 +358,12 @@ function sendRequest(command, data, host = sessionHost) {
...
-                    // Remove the type prefix from the error message (e.g. "Error: ").
-                    responeMessage = response.message.replace(/^[a-z]+: /i, '');
-                }
-
-                const exceptionToReport = new Error(responeMessage);
-                Object.assign(exceptionToReport, responseError);
-                throw exceptionToReport;
+            if (error && typeof error === "string") {
+                error = error.replace(/^[a-z]+: /i, "");
+            } else if (error.type && error.type === "error") {
```
Comment (blagoev) [inline lib/browser/rpc.js:363]: Just to confirm we are sure we don't have this case anymore?
`error.type && error.type === 'dict'`

File: src/jsc/jsc_rpc_network_transport.hpp (hunk 10 above)
Comment (blagoev) [reply src/jsc/jsc_rpc_network_transport.hpp:36]: The way I see it is we have JavaScriptNetworkTransport which is a generic class to do network requests. It should be possible to use it instead of defining a new one for the debug context. The way it works is it just needs a `global.Realm._networkTransport.fetchWithCallbacks` in order to work.

Comment (kraenhansen) [reply src/jsc/jsc_rpc_network_transport.hpp:36]: That was my initial thought as well. However it turned out to be way easier to implement an alternative specialisation of `GenericNetworkTransport` than providing a polyfill for `fetchWithCallbacks` implemented in C++. I'm sure you would have reached the same conclusion. From your comment, I don't see sufficient value in changing this approach and I'll leave it at this.

File: lib/browser/rpc.js (hunk 16 above)
Comment (kraenhansen) [reply lib/browser/rpc.js:363]: We should definitely refrain from throwing anything other than instances of `Error` (or a subclass thereof).
If we do,  that will proceed to line 369 - so an error will be thrown client side, although that will probably be with a strange message:

    Error: [object Object]

Comment (blagoev) [reply lib/browser/rpc.js:363]: aren't we throwing an instance of Error in the old implementation. Seems we are
https://github.com/realm/realm-js/pull/3411/files#diff-1aeca8a83cdc5d4f7bf6859366830e44c8acbd0269a540bef9194be798436902L348
I wonder if the case with this check is still valid
`error.type && error.type === 'dict'`

Comment (kraenhansen) [reply lib/browser/rpc.js:363]: > aren't we throwing an instance of Error in the old implementation.

We are, but that would be serialized to a 'dict' which deserialized to a regular object on the client side, which would then be wrapped in an Error.

> We should definitely refrain from throwing anything other than instances of Error (or a subclass thereof).

This comment was to the native code. It's the only way I can see the `error.type` would be "dict" after this PR.

File: src/rpc.cpp (hunk 6 above)
Comment (blagoev) [reply src/rpc.cpp]: ok resolving

File: src/js_app.hpp (hunk 8 above)
Comment (blagoev) [reply src/js_app.hpp]: I see this is fixed. resolving

File: lib/browser/rpc.js (hunk 16 above)
Comment (blagoev) [reply lib/browser/rpc.js:363]: ok. resolving

**Review by blagoev — APPROVED** [review]
approving the changes since my comments are already worked on

File: src/js_app.hpp (hunk 4 above)
Comment (Muzzamil75) [reply src/js_app.hpp]: keep up the good work guys. Anxiously waiting for this bug fix ! @kneth  @kraenhansen

**Review by cesarvr — APPROVED** [review]
LGTM

**Comment by kraenhansen** [comment]
I've added static members to the `AppClass` and exposed a `_setVersions` static method on it to set it from the outside as well as over the RPC bridge. I considered calling the `set_versions` method from `rpc.cpp`, but it turned out more complicated than setting the static members on the `AppClass` directly.

**Review by kneth — APPROVED** [review]

**Comment by kraenhansen** [comment]
I found (and solved a bug) where fetching would cause a "EXC_BAD_ACCESS" (the function got called in a released context).

File: src/rpc.cpp [hunk 17]
```diff
@@ -624,6 +624,9 @@ RPCServer::~RPCServer() {
     m_objects.clear();
     m_callbacks.clear();
 
+    // Clear the Object Store App cache, to prevent instances from using the context which is going to be released.
+    app::App::clear_cached_apps();
```
Comment (kraenhansen) [inline src/rpc.cpp:628]: I am a bit unsure if this is the right place to call it.
I'm unaware of another place in our code that gets called when we're "unloading" our library, but we could clear the object store app cache when we initialize instead? https://github.com/realm/realm-js/blob/master/src/jsc/jsc_init.cpp#L42

Comment (kraenhansen) [reply src/rpc.cpp:628]: @blagoev @kneth ☝️ what do you think about that?

Comment (kneth) [reply src/rpc.cpp:628]: I imagine the issue is when you reload the app, right? If so, I think it make sense to clear the cache as you shut down the RPC server.

Comment (kraenhansen) [reply src/rpc.cpp:628]: Correct. If it's not cleared before / after a reload object store might be reusing app instances that reference a context which has been garbage collected.

Comment (kneth) [reply src/rpc.cpp:629]: :+1:

**Comment by kneth** [comment]
LGTM - merge at will!

**Review by cesarvr — APPROVED** [review]

**Review by fronck — COMMENTED** [review]
In general:  I think we should make an effort to document functions -- at least new ones -- with e.g., Doxygen-style headers to improve the general developer-friendlyness of the codebase.


Otherwise, good job; LGTM.

**Comment by mendesbarreto** [comment]
Thank you all for this work!!!

**Comment by saivarunk** [comment]
When can we expect this commit/version to be published on npm?

**Comment by kraenhansen** [comment]
@saivarunk it's out in [v10.0.2](https://github.com/realm/realm-js/releases/tag/v10.0.2).
