### PR TITLE
Fixes for RN 0.31.0

### LINKED ISSUE #551: react-native 0.31-rc
Use of undeclared identifier 'class_getInstanceVariable'

### PR DESCRIPTION
**Pull request by alazier**
Fixes #551

### CODE REVIEW

**Comment by alazier** [comment]
@bdash can you review?

File: react-native/ios/RealmReact/RealmReact.mm [hunk 1]
```diff
@@ -69,7 +71,7 @@ - (JSGlobalContextRef)ctx;
         object_setIvar(executor, contextIvar, rctJSContext);
     }
 
-    return [rctJSContext ctx];
+    return [rctJSContext context].JSGlobalContextRef;
```
Comment (bdash) [inline react-native/ios/RealmReact/RealmReact.mm]: Does this `-context` method exist in all supported versions of React Native?

Comment (fealebenpae) [inline react-native/ios/RealmReact/RealmReact.mm]: Yes, it has been added quite a while ago: https://github.com/facebook/react-native/commit/45d2c691a3433bd77cc665367c5d37de19aaffcc

Comment (alazier) [inline react-native/ios/RealmReact/RealmReact.mm]: It does. Looks like it has been around since 0.14.0. We should have been using it earlier but its addition was unnoticed.

**Comment by fealebenpae** [comment]
👍

**Comment by bdash** [comment]
👍
