### PR TITLE
Kneth/bugs/schema version

### LINKED ISSUE #6119: Realm.schemaVersion returns 18446744073709552000 instead of -1 in test
### How frequently does the bug occur?

Always

### Description

I use jest to test the realm related logic. Since Realm v12, some of tests start failing because Realm.schemaVersion doesn't return -1 if realm file doesn't exist.  Below is a quick test to show the issue.

```
expect(Realm.schemaVersion('./default.realm')).toBe(-1)

-------------------------------------
Expected: -1
Received: 18446744073709552000

```

It works as expected in our react-native app. 

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Always

### Reproduction Steps

_No response_

### Version

12.1.0

### What services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Mac OS 13.5.1 (22G90)

### Build environment

RN 0.71.13

### Cocoapods version

1.12.1

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

This closes #6119 

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [x] 🚦 Tests
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

**Review by takameyer — APPROVED** [review]
LGTM :shipit:

File: packages/realm/src/Realm.ts [hunk 1]
```diff
@@ -376,13 +376,17 @@ export class Realm {
...
     const config: Configuration = { path };
     const absolutePath = Realm.determinePath(config);
     const schemaVersion = binding.Realm.getSchemaVersion({
       path: absolutePath,
       encryptionKey: Realm.determineEncryptionKey(encryptionKey),
     });
-    return binding.Int64.intToNum(schemaVersion);
+    // no easy way to compare uint64_t in TypeScript
+    return notFound.toString() === schemaVersion.toString()
+      ? binding.Int64.intToNum(-1)
```
Comment (elle-j) [inline packages/realm/src/Realm.ts:388]:
```suggestion
      ? -1
```

**Review by elle-j — APPROVED** [review]
Good to get a fix in 👍
