### PR TITLE
Prevent node 19 to hang under installation

### LINKED ISSUE #5136: node 19 hangs when installing Realm
### How frequently does the bug occur?

Sometimes

### Description

Using node 19, `npm install realm` seems to hang.

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Not yet

### Reproduction Steps

```sh
nvm use 19
mkdir foobar
cd foobar
npm init -y
npm install realm
```

### Version

11.2.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOS, Linux

### Build environment

_No response_

### Cocoapods version

_No response_

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

node 19 changes default behaviour of https.get() so we set it to the old behaviour

This closes #5136 and #5547

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [ ] 🚦 Tests
* [ ] 🔀 Executed flexible sync tests locally if modifying flexible sync
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated

### CODE REVIEW

File: scripts/submit-analytics.js [hunk 1]
```diff
@@ -44,6 +44,7 @@
 const fs = require("fs");
 const fse = require("fs-extra");
 const path = require("path");
+const https = require("https");
```
Comment (elle-j) [inline scripts/submit-analytics.js:47]: Should we localize this import to only `submitAnalytics()` instead?

File: CHANGELOG.md [hunk 2]
```diff
@@ -8,6 +8,7 @@
 
 ### Fixed
 * It is not allowed to specify `deleteRealmIfMigrationIsNeeded` and sync. This can lead to error messages like `Schema validation failed due to the following errors`. ([#5548](https://github.com/realm/realm-js/issues/5548), v10.12.0)
+* Installation will hang when using Node 19. ([#5136](https://github.com/realm/realm-js/issues/5136), since v10.13.0)
```
Comment (elle-j) [inline CHANGELOG.md:11]: Possible reformulation:
```suggestion
* Installation will no longer hang when using Node 19. ([#5136](https://github.com/realm/realm-js/issues/5136), since v10.13.0)
```

File: scripts/submit-analytics.js [hunk 3]
```diff
@@ -215,30 +216,9 @@ async function collectPlatformData(packagePath = getProjectRoot()) {
 }
 
 /**
- * Send collected analytics data to Realm's servers over HTTPS
- * @param  {Object} payload analytics info
+ * Collect and Send analytics data to MongoDB over HTTPS
```
Comment (elle-j) [inline scripts/submit-analytics.js:219]:
```suggestion
 * Collect and send analytics data to MongoDB over HTTPS
```

File: scripts/submit-analytics.js [hunk 4]
```diff
@@ -259,7 +239,25 @@ async function submitAnalytics(dryRun) {
     return;
   }
 
-  await Promise.all([dispatchAnalytics(payload)]);
+  return new Promise((resolve, reject) => {
+    // node 19 turns on keep-alive by default and it will make the https.get() to hang
+    // https://github.com/realm/realm-js/issues/5136
+    https.globalAgent = new https.Agent({ keepAlive: false });
```
Comment (elle-j) [inline scripts/submit-analytics.js:245]: If we move the `https` import to this function, then it may be safer to override the `globalAgent`. E.g. thinking of a scenario where `https` is global in this file and by passing `{ keepAlive: false }` would set the other non-specified `option` values to their defaults right? (And perhaps override any changes made to these somewhere else in this file). Although, I assume this is an unlikely scenario. But localizing the `https` might still be favorable.

**Review by elle-j — APPROVED** [review]
No more infinite wait 🕐 😃

**Review by takameyer — APPROVED** [review]
LGTM.  Do we have tests activated for this?

File: scripts/submit-analytics.js [hunk 5]
```diff
@@ -259,7 +239,25 @@ async function submitAnalytics(dryRun) {
...
+    const requestUrl = getAnalyticsRequestUrl(payload);
+
+    https
+      .get(requestUrl, (res) => {
```
Comment (nirinchev) [inline scripts/submit-analytics.js:249]: Rather than overriding the global agent here, why not pass the custom agent to the `get` request options:

```suggestion
    const requestUrl = getAnalyticsRequestUrl(payload);

    https
      .get(requestUrl, { agent:  new https.Agent({ keepAlive: false }) }, (res) => {
```

**Comment by kneth** [comment]
@takameyer 

> Do we have tests activated for this?

Only my local test. Please note that node 19 is not in tier 1.

File: scripts/submit-analytics.js (hunk 4 above)
Comment (kneth) [reply scripts/submit-analytics.js]: I have accepted the suggestion by @nirinchev which is basically doing what you are saying.

**Comment by takameyer** [comment]
> Please note that node 19 is not in tier 1.

I think it would be great if we built a system of checking on the latest releases of the platforms we run on so that we are ahead of the breaking changes.  But that's something for another PR

**Comment by fukemy** [comment]
can u fix for 11.0.0-rc.0?
