### PR TITLE
Pass arguments correctly to callResetPasswordFunction

### LINKED ISSUE #4143: Cannot run reset password function using Node SDK
### How frequently does the bug occur?

All the time

### Description

I use NodeJS Realm SDK.

I expect my password reset function to be called when I do the following:
```
await app.emailPasswordAuth.callResetPasswordFunction('user@example.com', 'myNewPassword')
```
or at least when I use new API as this is described [here](https://github.com/realm/realm-js/issues/3943):
```
await app.emailPasswordAuth.callResetPasswordFunction({ email: 'user@example.com', password: 'myNewPassword' })
```
But both approaches result in the same error.
 

### Stacktrace & log output

```shell
Error: Error: resetDetails must be of type 'object', got (user@example.com)
at /myProject/node_modules/realm/lib/email-password-auth-methods.js:76:35
at /myProject/node_modules/realm/lib/utils.js:52:7
at new Promise (<anonymous>)
	at promisify (/myProject/node_modules/realm/lib/utils.js:51:12)
	at EmailPasswordAuth.callResetPasswordFunction (/myProject/node_modules/realm/lib/email-password-auth-methods.js:76:12)
	at _callee$ (/myProject/utils/resetPassword.js:11:31)
	at tryCatch (/myProject/node_modules/regenerator-runtime/runtime.js:63:40)
	at Generator.invoke [as _invoke] (/myProject/node_modules/regenerator-runtime/runtime.js:294:22)
	at Generator.next (/myProject/node_modules/regenerator-runtime/runtime.js:119:21)
	at asyncGeneratorStep (/myProject/utils/resetPassword.js:11:103)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Enable email/password auth for Realm Application
2. Configure it to run custom password reset function
3. Register a user
4. Try to run password reset function for registered user:
```
const app = new Realm.App({id: id})
await app.emailPasswordAuth.callResetPasswordFunction({ email: 'user@example.com', password: 'newUserPassword' })
```

### Version

10.10.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Debian GNU/Linux 9.13 (stretch)

### Build environment

_No response_

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

This closes #4143 

## ☑️ ToDos

* [x] 📝 Changelog entry
* ~[ ] 📝 `Compatibility` label is updated or copied from previous entry~
* [x] 🚦 Tests
* ~[ ] 📱 Check the React Native/other sample apps work if necessary~
* ~[ ] 📝 Public documentation PR created or is not necessary~
* ~[ ] 💥 `Breaking` label has been applied or is not necessary~
* [ ] Add `resetFunction` to the test set up (see https://docs.mongodb.com/realm/authentication/email-password/#run-a-password-reset-function)

*If this PR adds or changes public API's:*
* ~[ ] typescript definitions file is updated~
* ~[ ] jsdoc files updated~
* ~[ ] Chrome debug API is updated if API is available on React Native~

### CODE REVIEW

**Review by kraenhansen — APPROVED** [review]
If it passes, this looks reasonable :)

File: tests/js/user-tests.js [hunk 1]
```diff
@@ -272,6 +272,24 @@ module.exports = {
...
 
+  async testResetPassword() {
+    let app = new Realm.App(appConfig);
+
+    const validEmail = randomVerifiableEmail();
+    const validPassword = "password123456";
+    await app.emailPasswordAuth.registerUser({ email: validEmail, password: validPassword });
+
+    const newPassword = "realm_tests_do_reset654321";
+    await app.emailPasswordAuth.callResetPasswordFunction({ email: validEmail, password: newPassword });
```
Comment (tomduncalf) [inline tests/js/user-tests.js:283]: Would it be worthing adding another test which calls this with the optional extra `...args`? e.g. 

```
await app.emailPasswordAuth.callResetPasswordFunction({ email: validEmail, password: newPassword }, "test", 123);
```

I'm not sure if/how we could verify that the args are actually being passed to the function, but it would check that we don't get an error calling it at least

**Review by tomduncalf — APPROVED** [review]
Thanks for fixing this and adding a test!

File: tests/js/user-tests.js (hunk 1 above)
Comment (takameyer) [reply tests/js/user-tests.js:283]: I guess the function could send the args back in the resolved promise?

Comment (tomduncalf) [reply tests/js/user-tests.js:283]: Yeah that's a good idea – I actually have no idea how the Realm app for these tests comes into being (e.g. where the template which contains the password reset function is)!

**Review by fronck — APPROVED** [review]
LGTM is all is green 👍
