### PR TITLE
Fix accessing `providerType` via `User.identities`

### LINKED ISSUE #6248: Realm.User.identities is returning undefined providerType
### How frequently does the bug occur?

Always

### Description

When trying to access the providerType of a UserIdentity in Realm.User.identities, providerType is undefined.

https://github.com/realm/realm-js/blob/a3589c63a1d18740b4ffd7b18ca82b92a8ea33b5/packages/realm/src/app-services/User.ts#L191-L196C4

I think this could be fixed with:
realm-js/packages/realm/src/app-services/User.ts @193
```diff
- const { id, provider_type: providerType } = identity as Record<string, string>;
+ const { id, providerType } = identity as Record<string, string>;
```

because Realm.User.providerType (now deprecated) just accesses identity.providerType (not identity.provider_type)
https://github.com/realm/realm-js/blob/a3589c63a1d18740b4ffd7b18ca82b92a8ea33b5/packages/realm/src/app-services/User.ts#L141-L151C4

### Stacktrace & log output

_No response_

### Can you reproduce the bug?

Always

### Reproduction Steps

_No response_

### Version

12.3.0

### What services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

Yes

### Platform OS and version(s)

iOS 16

### Build environment

Which debugger for React Native: ..

### Cocoapods version

_No response_

### PR DESCRIPTION
**Pull request by elle-j**
## What, How & Why?

`providerType` was previously destructured using snake_case, but since we transform the generated types to use camelCase this caused `undefined` to always be returned.

This closes #6248 

## ☑️ ToDos
* [x] 📝 Changelog entry
* [x] 🚦 Tests

### CODE REVIEW

File: integration-tests/tests/src/tests/sync/user.ts [hunk 1]
```diff
@@ -16,30 +16,31 @@
...
+  expect(user).to.be.an("object");
+  expect(user.accessToken).to.be.a("string");
+  expect(user.refreshToken).to.be.a("string");
+  expect(user.id).to.be.a("string");
+  expect(user.customData).to.be.an("object");
   expect(user).instanceOf(Realm.User);
+  expect(user.identities).to.be.an("array");
+  if (providerType) {
+    expect(user.identities.some((identity) => identity.providerType === providerType)).to.be.true;
+  }
```
Comment (elle-j) [inline integration-tests/tests/src/tests/sync/user.ts:43]: We could also choose to move this to a separate function to keep the `expectIsUser` focused on type checking.

Comment (kraenhansen) [reply integration-tests/tests/src/tests/sync/user.ts:43]: I'd probably inline this in the test function instead 👍

**Review by kraenhansen — APPROVED** [review]

File: integration-tests/tests/src/tests/sync/user.ts (hunk 1 above)
Comment (kraenhansen) [reply integration-tests/tests/src/tests/sync/user.ts]: This is better IMO 👍

**Review by takameyer — APPROVED** [review]
