### PR TITLE
callFunction argument validation

### LINKED ISSUE #4623: SegFault when using callFunction()
There appears to be a segfault occuring when calling `callFunction` with the wrong parameters.  This should throw an error instead.

### PR DESCRIPTION
**Pull request by takameyer**
## What, How & Why?
A segmentation fault occurs when calling `callFunction` with invalid arguments.

This closes #4623

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 🔀 Executed flexible sync tests locally if modifying flexible sync
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

File: tests/js/user-tests.js [hunk 1]
```diff
@@ -332,7 +332,7 @@ module.exports = {
     let credentials = Realm.Credentials.anonymous();
     let user = await app.logIn(credentials);
 
-    TestCase.assertEqual(await user.callFunction("sumFunc"), 0);
+    TestCase.assertEqual(await user.callFunction("sumFunc", 123), 0);
```
Comment (kraenhansen) [inline tests/js/user-tests.js:335]: I would expect this to throw?

**Review by kraenhansen — APPROVED** [review]

File: tests/js/user-tests.js (hunk 1 above)
Comment (takameyer) [reply tests/js/user-tests.js:335]: Good catch.  I forgot to clean this up.

**Review by kneth — APPROVED** [review]
Please add a changelog entry
