### PR TITLE
Fixing "Right-hand side of 'instanceof' is not an object" and adding dictionary integration tests

### LINKED ISSUE #3836: `instanceof Realm.Dictionary` doesn't work on RN
If `dict` is a dictionary, `dict instanceof Realm.Dictionary` will be false on React Native (but not on node.js).

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

While debugging the alternative dictionary implementation last week, I wrote a couple of tests in our integration test suite.

This fixes #3836 and #3860.

## ☑️ ToDos
* [x] 📝 Changelog entry
* [x] 📝 `Compatibility` label is updated or copied from previous entry
* [x] 🚦 Tests
* [x] 📝 Public documentation PR created or is not necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

File: integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.m [hunk 1]
```diff
@@ -53,7 +53,7 @@ - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(
 - (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
 {
 #if DEBUG
-  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
+  return [NSURL URLWithString:[[[[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil] absoluteString] stringByAppendingString:@"&inlineSourceMap=true" ]];
```
Comment (kraenhansen) [inline integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.m:56]: I changed this to make it easier to debug JavaScript with Safari.

File: integration-tests/environments/react-native/package.json [hunk 2]
```diff
@@ -18,9 +18,8 @@
     "app-importer": "realm-app-importer serve ../../realm-apps",
     "metro": "react-native start --reset-cache",
     "runner": "node harness/runner.js",
-    "prepare": "npm run install-local && npm run pod-install",
-    "install-local": "npm_config_ignore_scripts=true install-local",
-    "pod-install": "cd ios && pod install"
+    "prepare": "npm run install-local && pod-install",
+    "install-local": "npm_config_ignore_scripts=true install-local"
```
Comment (kraenhansen) [inline integration-tests/environments/react-native/package.json:22]: Using the `pod-install` package makes it easier to run these on a non-mac machine.

File: integration-tests/tests/src/hooks/open-realm-before.ts [hunk 3]
```diff
@@ -29,23 +29,32 @@ export function openRealmBefore(config: LocalConfiguration | SyncedConfiguration
...
+    Realm.deleteFile(this.config);
+    delete this.config;
+  } else {
+    throw new Error("Expected a 'config' in the context");
+  }
+  // Clearing the test state to ensure the sync session gets completely reset and nothing is cached between tests
+  Realm.clearTestState();
+}
+
+export function openRealmBeforeEach(config: LocalConfiguration | SyncedConfiguration = {}) {
```
Comment (kraenhansen) [inline integration-tests/tests/src/hooks/open-realm-before.ts:52]: I did this refactor to make it easier to run this hook either `beforeEach` or `before`, but it turned out I didn't need it anyway.

File: integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.m (hunk 1 above)
Comment (kneth) [reply integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.m:56]: It makes sense since we are going to make this modification of a regular basis.

Comment (kneth) [reply integration-tests/environments/react-native/ios/RealmReactNativeTests/AppDelegate.m:56]: A comment about source map and Safari might be appropriate.

File: integration-tests/tests/src/tests/dictionary.ts [hunk 4]
```diff
@@ -0,0 +1,283 @@
...
+      const dictSchemaProperty = this.realm.schema[0].properties.dict as Realm.ObjectSchemaProperty;
+      expect(typeof dictSchemaProperty).equals("object");
+      expect(dictSchemaProperty.type).equals("dictionary");
+      expect(dictSchemaProperty.objectType).equals("mixed");
+    });
+  
+    it("is instanceof Dictionary", function(this: RealmContext) {
+      this.realm.write(() => {
+        const item = this.realm.create<Item>("Item", {});
+        expect(item.dict instanceof Realm.Dictionary);
```
Comment (kneth) [inline integration-tests/tests/src/tests/dictionary.ts:45]: So https://github.com/realm/realm-js/issues/3836 isn't a real issue?

**Review by kneth — APPROVED** [review]
Only minor comments and questions.

File: integration-tests/tests/src/tests/dictionary.ts (hunk 4 above)
Comment (kraenhansen) [reply integration-tests/tests/src/tests/dictionary.ts:45]: I at least cannot reproduce it.

File: integration-tests/tests/src/tests/dictionary.ts [hunk 5]
```diff
@@ -0,0 +1,315 @@
...
+    const methodNames = [
+      // "get",
+      "set",
+      "remove",
+      "addListener",
+      "removeListener",
+      "removeAllListeners",
+    ];
+    for (const name of methodNames) {
+      it(`expose a method named '${name}'`, function (this: RealmContext) {
```
Comment (takameyer) [inline integration-tests/tests/src/tests/dictionary.ts:79]:
```suggestion
      it(`exposes a method named '${name}'`, function (this: RealmContext) {
```

File: integration-tests/tests/src/tests/dictionary.ts [hunk 6]
```diff
@@ -0,0 +1,315 @@
...
+
+    it("can be used as a property type in a schema", function (this: RealmContext) {
+      expect(this.realm.isClosed).equals(false);
+      const dictSchemaProperty = this.realm.schema[0].properties.dict as Realm.ObjectSchemaProperty;
+      expect(typeof dictSchemaProperty).equals("object");
+      expect(dictSchemaProperty.type).equals("dictionary");
+      expect(dictSchemaProperty.objectType).equals("mixed");
+    });
+
+    it("is instanceof Dictionary", function (this: RealmContext) {
```
Comment (takameyer) [inline integration-tests/tests/src/tests/dictionary.ts:63]:
```suggestion
    it("is an instance of Dictionary", function (this: RealmContext) {
```

File: integration-tests/tests/src/tests/dictionary.ts [hunk 7]
```diff
@@ -0,0 +1,315 @@
...
+        item.dict.key1 = 1234;
+        item.dict.key2 = Number.MAX_VALUE;
+        item.dict.key3 = Number.MIN_VALUE;
+        expect(item.dict).deep.equals({
+          key1: 1234,
+          key2: Number.MAX_VALUE,
+          key3: Number.MIN_VALUE,
+        });
+        // Increments
+        item.dict.key1++;
```
Comment (takameyer) [inline integration-tests/tests/src/tests/dictionary.ts:112]: Is this a c++ operation?  If so shouldn't we also test `-- += -=`?  Also what happens with `item.dict.key1 + "one"`?

File: integration-tests/tests/src/tests/dictionary.ts [hunk 8]
```diff
@@ -0,0 +1,315 @@
...
+        });
+      });
+    });
+
+    it("is spreadable", function (this: RealmContext) {
+      this.realm.write(() => {
+        const item = this.realm.create<Item>("Item", {
+          dict: { key1: "hi" },
+        });
+        expect({ ...item.dict }).deep.equals({ key1: "hi" });
```
Comment (takameyer) [inline integration-tests/tests/src/tests/dictionary.ts:166]: What happens when we do `item.dict = { ...item.dict, key2: "hello" }` ?

File: integration-tests/tests/src/tests/dictionary.ts [hunk 9]
```diff
@@ -0,0 +1,315 @@
...
+        expect(item.dict).deep.equals({ key1: "hi" });
+        delete item.dict.key1;
+        expect(Object.keys(item.dict)).deep.equals([]);
+        // TODO: Investigate why this blocks
+        // expect(item.dict).deep.equals({});
+      });
+    });
+  });
+
+  function describeTypedSuite({ extraSchema = [], type, goodValues, badValues, expectedError }: TypedDictionarySuite) {
```
Comment (takameyer) [inline integration-tests/tests/src/tests/dictionary.ts:224]: I was a bit confused what the `TypedDictionarySuite` was when I started reading this code from top to bottom.  I think it would be might be more clear to break these tests into their own file `typed_dictionary.ts`.

**Review by takameyer — CHANGES_REQUESTED** [review]
Nice work here.  Just a few suggestions, comments and questions.

**Review by takameyer — APPROVED** [review]
Approved! 🚀 🎉 👍 💯
