### PR TITLE
Always invoke sync callbacks on the JavaScript thread

### LINKED ISSUE #804: Marshal sync callbacks onto the JS thread
Without this we get assertion failures in React Native on iOS and segmentation faults in JavaScriptCore on Android because the JavaScript state is not meant to be accessed on other threads.

### PR DESCRIPTION
**Pull request by fealebenpae**
Fixes #804

### CODE REVIEW

File: src/event_loop_dispatcher.hpp [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+
+#pragma once
+
+#include <queue>
+#include <tuple>
+#include <mutex>
+
+#include "util/event_loop_signal.hpp"
+
+namespace __apply_polyfill {
```
Comment (simonask) [inline src/event_loop_dispatcher.hpp]: Identifiers beginning with double underscores are reserved by the language (used by compilers for things like `__builtin_foo`).

File: src/event_loop_dispatcher.hpp [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+template <class Tuple, class F, size_t... Is>
+constexpr auto apply_impl(Tuple t, F f, std::index_sequence<Is...>) {
+    return f(std::get<Is>(t)...);
+}
+
+template <class Tuple, class F>
+constexpr auto apply(Tuple t, F f) {
```
Comment (simonask) [inline src/event_loop_dispatcher.hpp]: Add FIXME about removing this when `std::apply` is available. :)

File: src/event_loop_dispatcher.hpp [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+private:
+    struct State {
+    public:
+        State(std::function<void(Args...)> func) : m_func(func) { }
+        
+        const std::function<void(Args...)> m_func;
+        std::queue<Tuple> m_invocations;
+        std::mutex m_mutex;
+    };
+    const std::shared_ptr<State> m_state;
```
Comment (simonask) [inline src/event_loop_dispatcher.hpp]: Why `std::shared_ptr` and not a member variable?

File: src/event_loop_dispatcher.hpp [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+                std::unique_lock<std::mutex> lock(state->m_mutex);
+                while (!state->m_invocations.empty()) {
+                    auto& tuple = state->m_invocations.front();
+                    ::__apply_polyfill::apply(tuple, state->m_func);
+                    state->m_invocations.pop();
+                }
+            }
+        }
+    };
+    const std::shared_ptr<EventLoopSignal<Callback>> m_signal;
```
Comment (simonask) [inline src/event_loop_dispatcher.hpp]: Same, why `std::shared_ptr`?

File: src/event_loop_dispatcher.hpp [hunk 5]
```diff
@@ -0,0 +1,92 @@
...
+
+template <typename... Args>
+class EventLoopDispatcher<void(Args...)> {
+    using Tuple = std::tuple<typename std::remove_reference<Args>::type...>;
+private:
+    struct State {
+    public:
+        State(std::function<void(Args...)> func) : m_func(func) { }
+        
+        const std::function<void(Args...)> m_func;
```
Comment (simonask) [inline src/event_loop_dispatcher.hpp]: Wrapping things in an `std::function` seems unnecessary since you don't really use the `Args...` template pack for anything other than passing along to `std::function`. I suppose you could just replace `std::function<void(Args...)>` with a template paramter `F` as in the declaration.

Comment (fealebenpae) [inline src/event_loop_dispatcher.hpp]: My template parameter is exactly `void(const std::string&, const SyncConfig&, std::shared_ptr<SyncSession>)`, not the inferred type of a lambda or other callable. I don't think I'd be able to use it as storage.

File: src/event_loop_dispatcher.hpp (hunk 3 above)
Comment (fealebenpae) [inline src/event_loop_dispatcher.hpp]: The `EventLoopDispatcher` instance can be copied a number of times when stuffed in a `std::function` but I want it to use the same state.

File: src/event_loop_dispatcher.hpp (hunk 4 above)
Comment (fealebenpae) [inline src/event_loop_dispatcher.hpp]: `EventLoopSignal` is neither copyable, nor movable. What's more, the Android implementation inherits from `std::enable_shared_from_this` and relies on being stored in a `shared_ptr`.

File: src/event_loop_dispatcher.hpp (hunk 5 above)
Comment (simonask) [inline src/event_loop_dispatcher.hpp]: Oh okay, so the intention is that a user of the class will define the signature up front?

File: src/event_loop_dispatcher.hpp (hunk 3 above)
Comment (simonask) [inline src/event_loop_dispatcher.hpp]: :+1:

File: src/event_loop_dispatcher.hpp (hunk 5 above)
Comment (fealebenpae) [inline src/event_loop_dispatcher.hpp]: Yup, like in https://github.com/realm/realm-js/blob/8c61cc9d41aa302de700e58edb06786972b99aec/src/js_sync.hpp#L268.
