### PR TITLE
repopulate partitionValue on syncSession (v10)

### LINKED ISSUE #3155: MongoDB realm - realm.syncSession.config does not return entire config
## Goals

Trying to retrieve the current partitionValue from a sync session configuration on a realm instance.

## Expected Results

`realm.syncSession.config.partitionValue` to return the value of the partition key. 

## Actual Results

returns `undefined`

## Steps to Reproduce

run `realm.syncSession.config.partitionValue` on a synced realm.

## Version of Realm and Tooling

- Realm JS SDK Version: 10.0.0-beta.9
- Node: v12.13.0
- Client OS & Version: osx 10.13.6

### PR DESCRIPTION
**Pull request by steffenagger**
This closes #3155

Besides _"repopulate partitionValue on syncSession"_, this PR adds checks for `partitionValue`:
- string: must not be empty.
- number: must be a whole number `>= Number.MIN_SAFE_INTEGER` and `<= Number.MAX_SAFE_INTEGER`.

In particular I'm worried I've overlooked something in regards to changes to: src/js_types.hpp:
When converting from Int64 to a number, we switch to Long. Doing so we have a `max_precise_double`, but this doesn't align with `Number.MAX_SAFE_INTEGER`, which is defined as `Math.pow(2, 53) - 1`.
```c++
constexpr static int64_t max_precise_double = 1ll << 52;
```

### NOTE: Missing CHANGELOG entry.

### CODE REVIEW

File: src/js_sync.hpp [hunk 1]
```diff
@@ -62,11 +64,18 @@ static std::string partition_value_bson_to_string(typename T::Context ctx, typen
...
+            if (pv.length() == 0) {
+                throw std::runtime_error("partitionValue of type 'string' cannot be an empty string.");
+            }
             partition_bson = bson::Bson(pv);
         }
         else if (Value<T>::is_number(ctx, partition_value_value)) {
             auto pv = Value<T>::validated_to_number(ctx, partition_value_value);
-            partition_bson = bson::Bson(static_cast<int64_t>(pv));
+            if (pv < 0 || pv > JS_MAX_SAFE_INTEGER || fmod(pv, 1) != 0) {
+                throw std::runtime_error("partitionValue of type 'number' must be a whole number >= 0 and <= Number.MAX_SAFE_INTEGER.");
```
Comment (kneth) [inline src/js_sync.hpp:75]: I don't think "whole number" is a well-defined mathematical term. Maybe "natural number", "non-negative integer" or just "integer".

File: tests/js/session-tests.js [hunk 2]
```diff
@@ -829,20 +830,57 @@ module.exports = {
...
     },
 
-    testNullPartitionValue() {
-        const app = new Realm.App(appConfig);
-        const credentials = Realm.Credentials.anonymous();
+    async testAcceptedPartitionValueTypes() {
+        const testPartitionValues = [
+            Utils.genPartition(), // string
+            0,
+            Math.floor(Math.random() * Number.MAX_SAFE_INTEGER),
```
Comment (kneth) [inline tests/js/session-tests.js:837]: In general we should avoid random test input. It will make it much harder to reproduce a failing test.

**Review by kneth — APPROVED** [review]

File: src/js_sync.hpp (hunk 1 above)
Comment (steffenagger) [reply src/js_sync.hpp:75]: https://dictionary.cambridge.org/dictionary/english/whole-number 🤷‍♂️
Then I would suggests `"partitionValue of type 'number' must be a non-negative integer <= Number.MAX_SAFE_INTEGER."`?

File: tests/js/session-tests.js (hunk 2 above)
Comment (steffenagger) [reply tests/js/session-tests.js:837]: This was mostly to not only test the extremes, I'll replace it with a static "random" small number & a large number.

File: src/js_sync.hpp (hunk 1 above)
Comment (fronck) [reply src/js_sync.hpp:75]: I don't think the `fmod(pv, 1) != 0` guard is safe across compilers and architectures.  It may perform a division (is the user has't done so already), which is not guaranteed to return exact integers, even if the maths say it should.

I think a safer approach would be something like 

```
            auto pv = Value<T>::validated_to_number(ctx, partition_value_value);
            decltype(pv) fraction;
            partition_bson = bson::Bson(static_cast<int64_t>(pv));
            if (pv < 0 || pv > JS_MAX_SAFE_INTEGER || modf(pv, *fraction) > std::numeric_limits<decltype(pv)>::epsilon(); {
               ...
```

File: tests/js/session-tests.js (hunk 2 above)
Comment (fronck) [reply tests/js/session-tests.js:837]: ..  Or, alternatively, pre-generate a set of 40 random numbers, add the the extremes to the list and test on those..

**Comment by fronck** [comment]
LGTM if the `fmod()` comment is considered.

File: tests/js/session-tests.js (hunk 2 above)
Comment (steffenagger) [reply tests/js/session-tests.js:837]: That was the idea, although where you thought 40, I thought 2 - I'll try to find something mid way.

File: src/js_types.hpp [hunk 3]
```diff
@@ -616,8 +619,7 @@ inline typename T::Value Value<T>::from_bson(typename T::Context ctx, const bson
         // it to a plain js number if it is in the range where it can be done precisely, otherwise
         // we map to the bson.Long type which preserves the value, but is harder to use.
         const auto i64_val = value.operator int64_t();
-        constexpr static int64_t max_precise_double = 1ll << 52; // 52 bits mantissa + implicit leading 1 bit.
-        if (-max_precise_double <= i64_val && i64_val <= max_precise_double)
+        if (-JS_MAX_SAFE_INTEGER <= i64_val && i64_val <= JS_MAX_SAFE_INTEGER)
```
Comment (fronck) [inline src/js_types.hpp:622]: Does JS have an actual definitoin of "min safe integer"  (these are usually something like `-JS_MAX_SAFE_INTEGER - 1`)?

**Review by fronck — APPROVED** [review]
LGTM if comments are addressed.

File: src/js_sync.hpp (hunk 1 above)
Comment (steffenagger) [reply src/js_sync.hpp:75]: Thanks @fronck that's just what I needed. I'll test it out & update.

File: src/js_types.hpp (hunk 3 above)
Comment (steffenagger) [reply src/js_types.hpp:622]: Yes `-Number.MAX_SAFE_INTEGER === Number.MIN_SAFE_INTEGER` => `true`.

Comment (fronck) [reply src/js_types.hpp:622]: Great

File: src/js_sync.hpp (hunk 1 above)
Comment (steffenagger) [reply src/js_sync.hpp]: @fronck I've updated to the solution we discussed elsewhere.

Comment (steffenagger) [reply src/js_sync.hpp]: @cesarvr the last "stringification" you mention is into a bson/ejson format, so the type is preserved at that point.

File: src/js_sync.hpp [hunk 4]
```diff
@@ -62,11 +64,18 @@ static std::string partition_value_bson_to_string(typename T::Context ctx, typen
...
             std::string pv = Value<T>::validated_to_string(ctx, partition_value_value);
+            if (pv.length() == 0) {
+                throw std::runtime_error("partitionValue of type 'string' may not be an empty string.");
+            }
             partition_bson = bson::Bson(pv);
         }
         else if (Value<T>::is_number(ctx, partition_value_value)) {
             auto pv = Value<T>::validated_to_number(ctx, partition_value_value);
-            partition_bson = bson::Bson(static_cast<int64_t>(pv));
+            if (pv < 0.0 || pv > JS_MAX_SAFE_INTEGER || fmod(pv, 1.0) > 0.0) {
```
Comment (blagoev) [inline src/js_sync.hpp:74]: why do we need to validate the partition value to be an integer.

File: src/js_sync.hpp [hunk 5]
```diff
@@ -62,11 +64,18 @@ static std::string partition_value_bson_to_string(typename T::Context ctx, typen
...
+                throw std::runtime_error("partitionValue of type 'number' must be a non-negative integer <= Number.MAX_SAFE_INTEGER.");
+            }
+            auto pvi = static_cast<int64_t>(pv);
```
Comment (blagoev) [inline src/js_sync.hpp:77]: I would use `modf` and cast the integral part instead of casting pv. 
http://www.cplusplus.com/reference/cmath/modf/
```
double integerPart;
fractionalPart = modf(value, &integerPart);
```
and compare using the `fractionalPart > 0.0` and cast the `integerPart`

File: src/js_sync.hpp [hunk 6]
```diff
@@ -321,6 +330,8 @@ void SessionClass<T>::get_config(ContextType ctx, ObjectType object, ReturnValue
         ObjectType config = Object::create_empty(ctx);
         Object::set_property(ctx, config, "user", create_object<T, UserClass<T>>(ctx, new User<T>(session->config().user, nullptr))); // FIXME: nullptr is not an app object
         // TODO: add app id
+        bson::Bson partition_value_bson = bson::parse(session->config().partition_value);
```
Comment (blagoev) [inline src/js_sync.hpp:333]: why do we do a roundtrip to/from Bson. Can't we just use the `partition_value` and set it to `Object::set_property(ctx, config, "partitionValue"`

**Review by blagoev — COMMENTED** [review]
I have some comments before I LGTM

File: src/js_sync.hpp (hunk 4 above)
Comment (steffenagger) [reply src/js_sync.hpp:74]: As far as I'm informed, Sync doesn't support other numbers.

File: src/js_sync.hpp (hunk 6 above)
Comment (steffenagger) [reply src/js_sync.hpp:333]: `session->config().partition_value` is a serialized bson/ejson string (I believe this is a common interface for all SDKs to OS/Sync (?)), we could store the original value somewhere - but after going through the different approaches with @kneth, I went with parsing the value used by Sync.

File: src/js_sync.hpp (hunk 5 above)
Comment (steffenagger) [reply src/js_sync.hpp]: @fronck also suggested `modf`. I've updated to this way instead, but wouldn't the result be the same?

File: src/js_sync.hpp (hunk 4 above)
Comment (blagoev) [reply src/js_sync.hpp]: 👍

File: src/js_sync.hpp (hunk 6 above)
Comment (blagoev) [reply src/js_sync.hpp:334]: 👍

**Review by blagoev — APPROVED** [review]

File: src/js_sync.hpp (hunk 1 above)
Comment (cesarvr) [reply src/js_sync.hpp]: Hey @steffenagger that's ok, just wanted to understand that decimal removal validation when the value that comes is a ``number``.  

If you just want only whole numbers you can cast to ``int64_t`` and the number will lost decimal information and you just need to validate for the numerical constraint. 

```cpp
auto number = static_cast<int64_t>(pv)
if (pv < 0 || pv > JS_MAX_SAFE_INTEGER) {
 //throw exception.... 
}
partition_bson = bson::Bson(number);
```

If throwing exception on a decimal is a must then I would suggest: 

```cpp 
  //#include <cmath>
 //  for pv = 10.5;                                                                    
 if (pv < 0 || pv > JS_MAX_SAFE_INTEGER || std::floor(pv) != pv ) { // 10 != 10.5 
  //throw exception.... 
 }
 partition_bson = bson::Bson(pv);
```
I my opinion is simpler way to achieve that goal.

Cheers.

Comment (steffenagger) [reply src/js_sync.hpp]: Of course, ask away 🙂 (I'll answer to the best of my knowledge).

The exception is a must, as we want to inform the users if they are supplying an unsupported number-format (it would otherwise be completely hidden that we converted the inputted `10.5` to `10`).

The  `int64_t` cast is there to trigger the `Bson` constructor into creating a `Long`  for Sync (not a `Double`).

I do like the simpler `std::floor(pv) != pv` check, @blagoev & @fronck any comments on this?

**Review by cesarvr — APPROVED** [review]

File: src/js_sync.hpp (hunk 4 above)
Comment (steffenagger) [reply src/js_sync.hpp]: Seems like my information was wrong, will update...

File: src/js_sync.hpp (hunk 1 above)
Comment (cesarvr) [reply src/js_sync.hpp]: Nice, thanks for the update. 👍

**Review by kneth — APPROVED** [review]
