### PR TITLE
RJS-2852: Adding a `CallInvoker`-based scheduler for Core on React Native

### LINKED ISSUE #2655: Change listeners on Results should always update React Native UI
## Goals

A callback registered as a listener for changes on a Realm JS `Results` instance should always be able to trigger updates of the React Native UI.

## Expected Results

From a React Native app, when registering a callback on a `Results` object and calling `this.setState` on a component, I would expect the UI to always update.

## Actual Results

- The UI only updates 4 out of 5 times when the change listener fires.
- The bug seems to disappear if `this.setState` is the first method called in the callback.
- It's possible to trigger an update of the UI by touching / clicking the simulator.

## Steps to Reproduce & Code Sample

Initialize a new React Native app:

    npx react-native init Issue2655 --directory realm-js-issue-2655

Copy in the files below, install the dependencies

    cd realm-js-issue-2655
    npm install

Create an instance of ROS and update `constants.js`.

In one terminal, start the updater (a node process changing a realm every second) - in another start the app on iOS

    npm run updater
    npm run ios

The app has two modes: "interval" where a timer will update the state every second and "realm" where a change listener will be registered and the bug is observed.

Use [the Safari developer tools](https://facebook.github.io/react-native/docs/debugging#safari-developer-tools) to attach to the apps JSContext and observe the issue in the timeline:

// TODO: Add images of the timeline and call-stacks when running in the two modes.

### package.json
```javascript
{
  "name": "realm-js-issue-2655",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "lint": "eslint .",
    "updater": "cd updater && node index.js"
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "realm": "^3.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "eslint": "^6.5.1",
    "metro-react-native-babel-preset": "^0.56.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### App.js

```javascript
import React, {Component} from 'react';
import {Button, Text, View} from 'react-native';
import Realm from 'realm';

import {schema} from './schema';
import {NICKNAME, SERVER_URL} from './constants';

const SEQUENCE = 'abcdefghijklmn';

const styles = {
  mainView: {
    justifyContent: 'center',
    height: '100%',
    padding: 10,
  },
};

export default class App extends Component {
  index = 1;

  constructor(props) {
    super(props);
    this.state = {value: 'Not yet set', mode: 'interval'};
    this.modeChanged(this.state.mode);
  }

  componentDidMount() {
    // Open up the Realm
    this.openRealm().then(null, err => {
      console.error(`Failed to open Realm: ${err.message}`);
    });
  }

  componentDidUpdate(_, prevState) {
    const {mode} = this.state;
    if (prevState.mode !== mode) {
      this.modeChanged(mode);
    }
  }

  componentWillUnmount() {
    if (this.realm) {
      this.realm.close();
    }
  }

  render() {
    console.log(`Rendered: ${this.state.value}`);
    return (
      <View style={styles.mainView}>
        <Text>
          Realm is "{this.realm && !this.realm.isClosed ? 'open' : 'closed'}"
        </Text>
        <Text>Mode is "{this.state.mode}"</Text>
        <Text>Value is "{this.state.value}"</Text>
        <Button
          title={`Toggle mode to ${
            this.state.mode === 'interval' ? 'realm' : 'interval'
          }`}
          onPress={this.toggleMode}
        />
      </View>
    );
  }

  ensureUser = async () => {
    if (Realm.Sync.User.current) {
      return Realm.Sync.User.current;
    } else {
      const credentials = Realm.Sync.Credentials.nickname(NICKNAME, true);
      return Realm.Sync.User.login(SERVER_URL, credentials);
    }
  };

  openRealm = async () => {
    let user = await this.ensureUser();

    const config = user.createConfiguration({
      schema,
      sync: {
        url: '~/issue-2655',
        fullSynchronization: true,
      },
    });

    this.realm = new Realm(config);
    this.singletons = this.realm.objects('Singleton');
  };

  callback = results => {
    const [singleton] = results;
    if (singleton) {
      const {value} = singleton;
      console.log(`Value changed to ${value}`);
      this.setState({value}, () => {
        console.log(`State was changed to ${this.state.value}`);
      });
    }
  };

  toggleMode = () => {
    this.setState({
      mode: this.state.mode === 'interval' ? 'realm' : 'interval',
    });
  };

  modeChanged = mode => {
    // Clear the interval if its mode is not interval
    if (mode !== 'interval') {
      clearInterval(this.interval);
    }
    // Remove the listener if the mode is not realm
    if (mode !== 'realm' && this.singletons) {
      this.singletons.removeListener(this.callback);
    }
    // Handle mode being set to interval
    if (mode === 'interval') {
      this.interval = setInterval(() => {
        const value = SEQUENCE.substring(0, this.index);
        this.callback([{value}]);
        this.index++;
        if (this.index > SEQUENCE.length) {
          this.index = 1;
        }
      }, 1000);
    }
    // When the mode becomes "realm", add a listener with the callback
    if (mode === 'realm' && this.singletons) {
      console.log('Setting listeners on', this.singletons);
      this.singletons.addListener(this.callback);
    }
  };
}
```

### constants.js

```javascript
module.exports = {
  NICKNAME: 'realm-js-issue-2655',
  SERVER_URL: 'https://[...].cloud.realm.io/', // Go to https://cloud.realm.io/ create an instance
};
```

### schema.js

```javascript
module.exports = {
  schema: [
    {
      name: 'Singleton',
      properties: {
        value: 'string',
      },
    },
  ],
};
```

### updater/index.js

```javascript
const Realm = require('realm');

const {NICKNAME, SERVER_URL} = require('../constants');
const {schema} = require('../schema');

const SEQUENCE = 'ABCDEFGHIJKLMN';
let index = 1;

function update(realm) {
  // Remove the first element of the list and insert a new at the end
  realm.write(() => {
    const value = SEQUENCE.substring(0, index);
    console.log(`Changing value to "${value}"`);
    const [singleton] = realm.objects('Singleton');
    if (singleton) {
      singleton.value = value;
    } else {
      realm.create('Singleton', {value});
    }
    // Increment the index
    index++;
    // Reset when it gets out of bounds
    if (index > SEQUENCE.length) {
      index = 1;
    }
  });
  realm.syncSession.uploadAllLocalChanges().then(() => {
    console.log('Done uploading!');
  });
}

function login() {
  if (Realm.Sync.User.current) {
    return Realm.Sync.User.current;
  } else {
    const credentials = Realm.Sync.Credentials.nickname(NICKNAME, true);
    return Realm.Sync.User.login(SERVER_URL, credentials);
  }
}

async function run() {
  const user = await login();
  const config = user.createConfiguration({
    schema,
    sync: {
      url: '~/issue-2655',
      fullSynchronization: true,
    },
  });
  const realm = new Realm(config);
  // Start updating
  setInterval(() => {
    update(realm);
  }, 1000);
}

run().then(null, err => {
  console.error(err.stack);
  process.exit(1);
});
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.6.0
- Node or React Native: React Native (verified on iOS)
- Client OS & Version: N/A
- Which debugger for React Native: None

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

This implements a `realm::util::Scheduler` for the React Native platform through the React Native [CallInvoker](https://github.com/facebook/react-native/blob/5bb57eb2b3884ef0c60551ee80880d95814eb71c/packages/react-native/ReactCommon/callinvoker/ReactCommon/CallInvoker.h#L27) API.

It's my current understanding that all active implementations of this API that a React Native app will construct, utilize the [RuntimeSchedulerCallInvoker](https://github.com/facebook/react-native/blob/5bb57eb2b3884ef0c60551ee80880d95814eb71c/packages/react-native/ReactCommon/react/renderer/runtimescheduler/RuntimeSchedulerCallInvoker.cpp) which in turn drop into either [RuntimeScheduler_Legacy](https://github.com/facebook/react-native/blob/5bb57eb2b3884ef0c60551ee80880d95814eb71c/packages/react-native/ReactCommon/react/renderer/runtimescheduler/RuntimeScheduler_Legacy.cpp) or [RuntimeScheduler_Modern](https://github.com/facebook/react-native/blob/5bb57eb2b3884ef0c60551ee80880d95814eb71c/packages/react-native/ReactCommon/react/renderer/runtimescheduler/RuntimeScheduler_Modern.cpp), both of which have invariants that we want when Core schedules calling of listeners:
1. Running tasks using a [RuntimeExecutor](https://github.com/facebook/react-native/blob/5bb57eb2b3884ef0c60551ee80880d95814eb71c/packages/react-native/ReactCommon/runtimeexecutor/ReactCommon/RuntimeExecutor.h#L17-L26) (ensuring the function will be called when it is safe to do so)
2. Draining microtasks after execution (effectively solving https://github.com/facebook/react-native/issues/33006)
3. Reporting uncaught `JSError` exceptions via `handleJSError` (effectively solving https://github.com/realm/realm-js/issues/6772 on React Native)

This fixes #2655 and #3571 and #6772 on React Native (iOS and Android) and replace the workaround introduced with https://github.com/realm/realm-js/pull/4389, https://github.com/realm/realm-js/pull/4725 and https://github.com/realm/realm-js/pull/5258/commits/03c30e7c35cd0726b8ae975fb4129b2bb18d993f.

### CODE REVIEW

File: packages/realm/binding/jsi/react_scheduler.cpp [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+    void invoke(util::UniqueFunction<void()>&& func) override
+    {
+        m_js_call_invoker->invokeAsync(
+            // Using low priority to avoid blocking rendering
+            facebook::react::SchedulerPriority::LowPriority,
+            // Wrapping the func in a shared_ptr to ensure it outlives the invocation
+            [func = std::make_shared<util::UniqueFunction<void()>>(std::move(func))] {
+                (*func)();
+            });
+    }
```
Comment (tgoyne) [inline packages/realm/binding/jsi/react_scheduler.cpp:68]: `[ptr = func.release())] { util::UniqueFunction<void()>(ptr)(); }`

LowPriority seems suspect to me. We do want it to be below user input, but processing refreshes promptly is pretty important.

File: packages/realm/binding/jsi/react_scheduler.cpp [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+namespace realm::js::react_scheduler {
+
+using Scheduler = realm::util::Scheduler;
+
+// std::shared_ptr<facebook::react::CallInvoker> js_call_invoker_{};
+std::shared_ptr<Scheduler> scheduler_{};
+
+
+class ReactScheduler : public realm::util::Scheduler {
```
Comment (tgoyne) [inline packages/realm/binding/jsi/react_scheduler.cpp:36]: This is very minor, but this type and the global variable should be in an anonymous namespace so that the symbols are not exported.

File: packages/realm/binding/jsi/react_scheduler.cpp (hunk 1 above)
Comment (kraenhansen) [reply packages/realm/binding/jsi/react_scheduler.cpp:68]: These are the available values https://github.com/facebook/react-native/blob/8d0cbbf0e6435e0a29d1d5d218b93c9eef1a2dcd/packages/react-native/ReactCommon/callinvoker/ReactCommon/SchedulerPriority.h#L14-L20

```
enum class SchedulerPriority : int {
  ImmediatePriority = 1,
  UserBlockingPriority = 2,
  NormalPriority = 3,
  LowPriority = 4,
  IdlePriority = 5,
};
```

Unfortunately not greatly documented 🤔

Comment (tgoyne) [reply packages/realm/binding/jsi/react_scheduler.cpp:68]: Glancing at the implementation, it looks like it always runs the highest priority waiting task unless a lower priority task has hit a timeout (250ms for UserBlocking, 5s for Normal, 10s for Low). If there's some specific Normal priority thing that we know we need to not interrupt then using Low makes sense, but otherwise I would default to Normal?

Comment (kraenhansen) [reply packages/realm/binding/jsi/react_scheduler.cpp:68]:
```
[ptr = func.release())] { util::UniqueFunction<void()>(ptr)(); }
```

I try to refrain from c-style castings 🤔 It seems to work, but what ensure the original function owned by `func` ever gets destructed?

File: packages/realm/binding/apple/RealmReactModule.mm [hunk 3]
```diff
@@ -79,7 +79,7 @@ - (void)dealloc {
   // See https://github.com/facebook/react-native/pull/43396#issuecomment-2178586017 for context
```
Comment (kneth) [inline packages/realm/binding/apple/RealmReactModule.mm:79]: Should we remove the comments?

File: packages/realm/binding/apple/RealmReactModule.mm [hunk 4]
```diff
@@ -79,7 +79,7 @@ - (void)dealloc {
...
   // If it was, we could use the enablement of "microtasks" to avoid the overhead of calling the invokeAsync on every call from C++ into JS.
```
Comment (kneth) [inline packages/realm/binding/apple/RealmReactModule.mm:80]: Should we remove the comments?

**Review by kneth — APPROVED** [review]
It is a better solution that the old workaround.

Please include an entry in `CHANGELOG.md` - maybe under "Internal" if you don't consider it a bug fix.

File: .watchmanconfig [hunk 5]
```diff
@@ -3,6 +3,8 @@
     "react-native/node_modules",
     "packages/realm-web",
     "packages/realm-web-integration-tests",
-    ".wireit"
+    ".wireit",
+    "packages/realm/.wireit",
+    "integration-tests/environments/react-native-test-app/.wireit"
```
Comment (kraenhansen) [inline .watchmanconfig:8]: I got annoyed by these being indexed by watchman.

**Review by fealebenpae — APPROVED** [review]

File: packages/realm/binding/jsi/react_scheduler.cpp (hunk 1 above)
Comment (tgoyne) [reply packages/realm/binding/jsi/react_scheduler.cpp]: There's no casts involved there. That's constructing a new UniqueFunction using the impl pointer (which takes ownership of the pointer) and then immediately invoking it. The function is then destroyed at the end of the statement as it's an unnamed temporary.

Comment (kraenhansen) [reply packages/realm/binding/jsi/react_scheduler.cpp]: I don't know how I misread that as a cast 🙂 What about the case where the function is dropped and never called, that would leak the function, right? (since no new `UniqueFunction` takes ownership.

Comment (tgoyne) [reply packages/realm/binding/jsi/react_scheduler.cpp]: This relies on CallInvoker guaranteeing that it'll invoke the function it's given exactly once; more than once and it's a use-after-free and zero times is a memory leak. This is generally a very safe thing to rely on as basically everything gets way more complicated otherwise.

**Review by tgoyne — APPROVED** [review]
