### PR TITLE
Fix bug due to std::thread::id being reused

### LINKED ISSUE #473: Realm is already open in another context on this thread.
This message just started appearing. Sometimes refreshing the simulator will fix it but other times I have to quit the simulator and launch it again. 

Can you shed some light on what this error is and how to go about preventing it? 

Thanks. 

screenshot 2016-06-06 08 14 59

### PR DESCRIPTION
**Pull request by appden**
After a thread is destroyed, a thread id might be reused. This is true for pthread_self() and hence std::thread::id. We were hitting this in Chrome debug mode because the "worker" thread was being destroyed and a new one immediately created when reloading. The thread id would be the same, and therefore we'd get back the SharedRealm for the previously destroyed thread (which had yet to be garbage collected.

The new implementation uses an atomically incremented, thread-local identifier, which serves our needs very well.

Fixes #473

### CODE REVIEW

**Comment by alazier** [comment]
What's going on with ci?

**Comment by alazier** [comment]
The code looks fine but we should ensure the ci issues are not indicative of a real issue.

**Comment by bdash** [comment]
The CI failure looks like a real issue:
```
/Users/realm/workspace/js_pr/configuration/Debug/target/realmjs/src/object-store/src/util/thread_id.hpp:36:12: error: thread-local storage is not supported for the current target
    static REALM_THREAD_LOCAL thread_id_t thread_id = 0;
           ^
In file included from /Users/realm/workspace/js_pr/configuration/Debug/target/realmjs/src/object-store/src/impl/list_notifier.cpp:19:
In file included from /Users/realm/workspace/js_pr/configuration/Debug/target/realmjs/src/object-store/src/impl/list_notifier.hpp:22:
In file included from /Users/realm/workspace/js_pr/configuration/Debug/target/realmjs/src/object-store/src/impl/collection_notifier.hpp:24:
In file included from ../core/include/realm/group_shared.hpp:29:
../core/include/realm/util/features.h:178:30: note: expanded from macro 'REALM_THREAD_LOCAL'
#  define REALM_THREAD_LOCAL __thread
```

**Comment by appden** [comment]
This was caught because CI tests on iPhone 4s, which turns out to not even support `__thread`, same with iPhone 5 targets. I just pushed a fix for that.

File: src/object-store/src/util/thread_id.hpp [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+#else
+#define REALM_HAS_THREAD_LOCAL 0
+#include <pthread.h>
+#endif
+
+namespace realm {
+
+using thread_id_t = std::size_t;
+
+namespace _impl {
```
Comment (bdash) [inline src/object-store/src/util/thread_id.hpp]: IMO there's enough going on in this header now that it'd be worth moving most of it to a .cpp file.

Comment (appden) [inline src/object-store/src/util/thread_id.hpp]: I actually disagree because `get_thread_id()` is a very hot function that should be inlined, and have its implementation inlined, as much as possible. Also, `ThreadLocal` is a class template.

Comment (bdash) [inline src/object-store/src/util/thread_id.hpp]: I'm skeptical that `get_thread_id` is so hot that the cost of a single function call is unbearable. I'd love to see the data you've gathered on this.

Comment (appden) [inline src/object-store/src/util/thread_id.hpp]: Honestly, I think `verify_thread()` should be inlined as well, and I think it should be called on property access to objects. I set a breakpoint and saw it called over 5000 times during our test suite. That's all the data I have. This is a pretty silly argument though. It's a very small utility function that makes sense to stay in a header given the existing style of the rest of the object store codebase.

Comment (bdash) [inline src/object-store/src/util/thread_id.hpp]: I didn't expect this to be a contentious point. If it were only the ~5 line function itself I'd agree it's not worth it, but the fact there's 10x that in supporting code is why i suggested moving it to a .cpp file.

Comment (alazier) [inline src/object-store/src/util/thread_id.hpp]: The other object store code base in headers is there because of the use of
templates. Anything more than a few lines should go in a cpp file when
possible.

File: src/object-store/src/util/thread_id.hpp [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+
+#if !REALM_HAS_THREAD_LOCAL
+template<typename T>
```
Comment (alazier) [inline src/object-store/src/util/thread_id.hpp]: Does this even need to be templated?

File: src/RealmJS.xcodeproj/project.pbxproj [hunk 3]
```diff
@@ -69,6 +69,8 @@
 		F63FF3261C1642BB00B3B8E0 /* GCDWebServerFileResponse.m in Sources */ = {isa = PBXBuildFile; fileRef = F63FF3181C1642BB00B3B8E0 /* GCDWebServerFileResponse.m */; };
 		F63FF3271C1642BB00B3B8E0 /* GCDWebServerStreamedResponse.m in Sources */ = {isa = PBXBuildFile; fileRef = F63FF31A1C1642BB00B3B8E0 /* GCDWebServerStreamedResponse.m */; };
 		F64A059B1D10D928004ACDBE /* format.cpp in Sources */ = {isa = PBXBuildFile; fileRef = 02E008D21D10AB1B00F3AA37 /* format.cpp */; };
+		F64A059D1D13710C004ACDBE /* thread_id.cpp in Sources */ = {isa = PBXBuildFile; fileRef = F64A059C1D13710C004ACDBE /* thread_id.cpp */; };
```
Comment (alazier) [inline src/RealmJS.xcodeproj/project.pbxproj]: why twice?

File: src/object-store/src/util/thread_id.cpp [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+
+#include <atomic>
+
+using namespace realm;
+
+// Since std::thread::id may be reused after a thread is destroyed, we use
+// an atomically incremented, thread-local identifier instead.
+thread_id_t realm::util::get_thread_id() {
+    static std::atomic<thread_id_t> id_counter;
+    static REALM_THREAD_LOCAL_TYPE(thread_id_t) thread_id = 0;
```
Comment (alazier) [inline src/object-store/src/util/thread_id.cpp]: would prefer `using` or `typedef` instead of the macro `REALM_THREAD_LOCAL_TYPE`

**Comment by alazier** [comment]
merge this and we can revisit the threadlocal stuff again later.

**Comment by bdash** [comment]
The [What's New In LLVM](https://developer.apple.com/videos/play/wwdc2016/405/) WWDC session suggests that while C++ `thread_local` was not supported, C11's `_Thread_local` is supported. A quick test shows that `_Thread_local` does not give the same "thread-local storage is not supported for the current target" errors that `thread_local` causes. That may result in a clean solution to this after all.

**Comment by appden** [comment]
@bdash `_Thread_local` still fails for iPhone 5 and below on Xcode 7 (haven't installed Xcode 8 yet).

**Comment by bdash** [comment]
Yeah, it does seem like 32-bit ARM devices only support `_Thread_local` when their minimum iOS version is set to iOS 9.0 or higher.
