### PR TITLE
Fix for Mixed binary roundtrip issue (#4278)

### LINKED ISSUE #4278: "roundtrip of ‘data'" mixed test case fails
When running the `mixed.ts` tests, the test for "roundtrip of 'data'" is failing:

```
[mocha]       AssertionError: expected [ 0, 0, 0, 0 ] to deeply equal [ 4, 8, 12, 16 ]
[mocha]       + expected - actual
[mocha]
[mocha]        [
[mocha]       -  0
[mocha]       -  0
[mocha]       -  0
[mocha]       -  0
[mocha]       +  4
[mocha]       +  8
[mocha]       +  12
[mocha]       +  16
[mocha]        ]
[mocha]
```
and on another run...

```
[mocha]       AssertionError: expected [ 43, 121, 236, 62 ] to deeply equal [ 4, 8, 12, 16 ]
[mocha]       + expected - actual
[mocha]
[mocha]        [
[mocha]       -  43
[mocha]       -  121
[mocha]       -  236
[mocha]       -  62
[mocha]       +  4
[mocha]       +  8
[mocha]       +  12
[mocha]       +  16
[mocha]        ]
```

This looks like it could be a memory corruption bug similar to previous issues found with the mixed data type.

### PR DESCRIPTION
**Pull request by fronck**
## What, How & Why?
Fixed issue that could cause mangling of binary data on a roundtrip to/from the database

This closes #4278

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [x] 🚦 Tests
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Review by kraenhansen — APPROVED** [review]

**Comment by fronck** [comment]
> I ran the integration tests locally and they pass 🎉 While this PR doesn't solve all problems with our mixed implementation I think this is a great step in the right direction.

Agreed.  There's still stuff to work out in our over-engineered Binary handling.

File: tests/js/mixed-tests.js [hunk 1]
```diff
@@ -224,4 +224,35 @@ module.exports = {
 
     realm.close();
   },
+
+  // test Nixed datatype with binary data contents
```
Comment (tomduncalf) [inline tests/js/mixed-tests.js:228]:
```suggestion
  // test Mixed datatype with binary data contents
```

**Review by tomduncalf — APPROVED** [review]
